//Stationary
export const equipmentTypeOptions = [
  { value: "Additive Blending Line Heaters", label: "Additive Blending Line Heaters" },
  { value: "Adhesive Curing Oven", label: "Adhesive Curing Oven" },
  { value: "Airport Ground Generator", label: "Airport Ground Generator" },
  { value: "Amine Reboilers", label: "Amine Reboilers" },
  { value: "Ammonia or Methanol Synthesis Furnace", label: "Ammonia or Methanol Synthesis Furnace" },
  { value: "Animal Cremator", label: "Animal Cremator" },
  { value: "Annealing Furnace", label: "Annealing Furnace" },
  { value: "Aquaculture Heater", label: "Aquaculture Heater" },
  { value: "Asphalt Blowing Stills (if fired)", label: "Asphalt Blowing Stills (if fired)" },
  { value: "Asphalt Heater", label: "Asphalt Heater" },
  { value: "Autoclaves with Fuel-Fired Boilers", label: "Autoclaves with Fuel-Fired Boilers" },
  { value: "Auto-thermal Reformers (ATRs)", label: "Auto-thermal Reformers (ATRs)" },
  { value: "Auxiliary Boilers", label: "Auxiliary Boilers" },
  { value: "Backup/Standby Generators", label: "Backup/Standby Generators" },
  { value: "Bakery Oven", label: "Bakery Oven" },
  { value: "Bench-scale Combustion Units", label: "Bench-scale Combustion Units" },
  { value: "BioFuel Based Generator", label: "BioFuel Based Generator" },
  { value: "Biogas/Landfill Gas Engines", label: "Biogas/Landfill Gas Engines" },
  { value: "Biohazard Incinerator", label: "Biohazard Incinerator" },
  { value: "Biomass Boilers", label: "Biomass Boilers" },
  { value: "Bitumen / Tar Heater Units", label: "Bitumen / Tar Heater Units" },
  { value: "Blast Furnace", label: "Blast Furnace" },
  { value: "Brewing Kettle", label: "Brewing Kettle" },
  { value: "Brick Kilns", label: "Brick Kilns" },
  { value: "Building Heating Furnaces/Stoves", label: "Building Heating Furnaces/Stoves" },
  { value: "Campus Boiler", label: "Campus Boiler" },
  { value: "Catalytic Oxidizers", label: "Catalytic Oxidizers" },
  { value: "Catalytic Reforming Catalyst Regeneration Kilns", label: "Catalytic Reforming Catalyst Regeneration Kilns" },
  { value: "Catering Oven", label: "Catering Oven" },
  { value: "Caustic Recovery Unit", label: "Caustic Recovery Unit" },
  { value: "Cement Kiln", label: "Cement Kiln" },
  { value: "Ceramic Kilns", label: "Ceramic Kilns" },
  { value: "Charcoal Grill", label: "Charcoal Grill" },
  { value: "Charge Heaters", label: "Charge Heaters" },
  { value: "Cheese Vat Heater", label: "Cheese Vat Heater" },
  { value: "Chemical Reactor Heater", label: "Chemical Reactor Heater" },
  { value: "CHP (Combined Heat and Power) Units", label: "CHP (Combined Heat and Power) Units" },


  // { value: "Claus Plant Burners (Sulfur Recovery Units)", label: "Claus Plant Burners (Sulfur Recovery Units)" },
  { value: "Coal Fired Boiler", label: "Coal Fired Boiler" },
  { value: "Coffee Roaster", label: "Coffee Roaster" },
  { value: "Cogeneration Plant", label: "Cogeneration Plant" },
  { value: "Coke Oven", label: "Coke Oven" },
  { value: "Combined Cycle Heat Recovery Steam Generators (HRSGs)", label: "Combined Cycle Heat Recovery Steam Generators (HRSGs)" },
  { value: "Combined Heat & Power (CHP) Units in Buildings", label: "Combined Heat & Power (CHP) Units in Buildings" },
  { value: "Combustion Turbines", label: "Combustion Turbines" },
  { value: "Combustion Turbines (for Power or Mechanical Drive)", label: "Combustion Turbines (for Power or Mechanical Drive)" },
  { value: "Construction Site Generator", label: "Construction Site Generator" },
  { value: "Cooking Range", label: "Cooking Range" },
  { value: "Crematoria Furnaces", label: "Crematoria Furnaces" },
  { value: "Crude Heaters", label: "Crude Heaters" },
  { value: "Crude Oil Heaters", label: "Crude Oil Heaters" },
  { value: "Cupola Furnaces", label: "Cupola Furnaces" },
  { value: "Dairy Pasteurizer", label: "Dairy Pasteurizer" },
  { value: "Dehydrogenation Reactor Furnaces", label: "Dehydrogenation Reactor Furnaces" },
  { value: "Desalter Heaters", label: "Desalter Heaters" },
  { value: "DG Set", label: "DG Set" },
  { value: "Diesel Engines", label: "Diesel Engines" },
  { value: "Diesel Furnace", label: "Diesel Furnace" },
  { value: "Diesel Generators", label: "Diesel Generators" },
  { value: "Direct-fired Oxidizers", label: "Direct-fired Oxidizers" },
  { value: "Distillation Unit", label: "Distillation Unit" },
  { value: "District Heating Plants (Onsite)", label: "District Heating Plants (Onsite)" },
  { value: "Drying Oven", label: "Drying Oven" },
  { value: "Dual-fuel Engines", label: "Dual-fuel Engines" },
  { value: "Electric Generator (Gas)", label: "Electric Generator (Gas)" },
  { value: "Emergency Backup Generator", label: "Emergency Backup Generator" },
  { value: "Ethylene Cracking Furnaces", label: "Ethylene Cracking Furnaces" },
  { value: "Ethylene Quench Furnaces", label: "Ethylene Quench Furnaces" },
  { value: "FCC (Fluid Catalytic Cracking) Unit Regenerators", label: "FCC (Fluid Catalytic Cracking) Unit Regenerators" },
  { value: "Fermentation Heater", label: "Fermentation Heater" },
  { value: "Field-Erected Boilers", label: "Field-Erected Boilers" },
  { value: "Fired Experimental Reactors", label: "Fired Experimental Reactors" },
  { value: "Fired Heaters (e.g., for Distillation Units)", label: "Fired Heaters (e.g., for Distillation Units)" },
  { value: "Fired Reboilers (vs. Steam-Heated Ones)", label: "Fired Reboilers (vs. Steam-Heated Ones)" },
  { value: "Fired Vaporizers (e.g., LNG or Cryogenic Gas Applications)", label: "Fired Vaporizers (e.g., LNG or Cryogenic Gas Applications)" },
  { value: "Fish Dryer", label: "Fish Dryer" },

  { value: "Flare Gas Recovery Combustors (Non-Flaring Systems)", label: "Flare Gas Recovery Combustors (Non-Flaring Systems)" },
  { value: "Flare Pilots (Continuous Gas Burners)", label: "Flare Pilots (Continuous Gas Burners)" },
  { value: "Food Cart Stove", label: "Food Cart Stove" },
  { value: "Food Dryers", label: "Food Dryers" },
  { value: "Food Processing Oven", label: "Food Processing Oven" },
  { value: "Fuel-fired Pellet Dryers", label: "Fuel-fired Pellet Dryers" },
  { value: "Gas Flaring Units (Controlled/Operated by Company)", label: "Gas Flaring Units (Controlled/Operated by Company)" },
  { value: "Gas Generators", label: "Gas Generators" },
  { value: "Gas Lift Compressor Drivers (Fuel-Fired)", label: "Gas Lift Compressor Drivers (Fuel-Fired)" },
  { value: "Gas- or Oil-Fired Space Heaters", label: "Gas- or Oil-Fired Space Heaters" },
  { value: "Gas Sweetening Reboilers (if Direct-Fired)", label: "Gas Sweetening Reboilers (if Direct-Fired)" },
  { value: "Gas Turbine", label: "Gas Turbine" },
  { value: "Gas-Fired Reciprocating Engines (for Compressors)", label: "Gas-Fired Reciprocating Engines (for Compressors)" },
  { value: "Glass Furnace", label: "Glass Furnace" },
  { value: "Glass-lined Reactor Heating Systems (Legacy Fuel-Fired)", label: "Glass-lined Reactor Heating Systems (Legacy Fuel-Fired)" },
  { value: "Glycol Reboilers", label: "Glycol Reboilers" },
  { value: "Grain Dryer", label: "Grain Dryer" },
  { value: "Granulation Dryers (Fuel-Fired Tray or Fluidized Dryers)", label: "Granulation Dryers (Fuel-Fired Tray or Fluidized Dryers)" },
  { value: "Greenhouse Boiler", label: "Greenhouse Boiler" },
  { value: "Heat Treatment Furnace", label: "Heat Treatment Furnace" },
  { value: "Heated Separators / Heater Treaters", label: "Heated Separators / Heater Treaters" },
  { value: "Heaters & Furnaces", label: "Heaters & Furnaces" },
  { value: "Hospital Sterilizer", label: "Hospital Sterilizer" },
  { value: "Hot Air Sterilizers (Fuel-Fired Versions)", label: "Hot Air Sterilizers (Fuel-Fired Versions)" },
  { value: "Hot Oil /Water Boilers", label: "Hot Oil /Water Boilers" },
  { value: "Hot Water Heater", label: "Hot Water Heater" },
  { value: "Hotel Boiler", label: "Hotel Boiler" },
  { value: "HVAC Reheat Coils (Fuel-Assisted)", label: "HVAC Reheat Coils (Fuel-Assisted)" },
  { value: "Incinerator", label: "Incinerator" },
  { value: "Incinerators (Hazardous Waste, Municipal Solid Waste)", label: "Incinerators (Hazardous Waste, Municipal Solid Waste)" },
  { value: "Incinerators for Expired Drugs / Hazardous Waste", label: "Incinerators for Expired Drugs / Hazardous Waste" },
  { value: "Industrial Boilers (Coal, Oil, Gas, Biomass)", label: "Industrial Boilers (Coal, Oil, Gas, Biomass)" },
  { value: "Industrial Dryer", label: "Industrial Dryer" },
  { value: "Industrial Kiln", label: "Industrial Kiln" },
  { value: "Industrial Ovens (Baking, Curing, Drying)", label: "Industrial Ovens (Baking, Curing, Drying)" },
  { value: "Kerosene Heater", label: "Kerosene Heater" },
  { value: "Lab Furnace", label: "Lab Furnace" },
  { value: "Laundry Dryer", label: "Laundry Dryer" },
  { value: "Lime Kilns", label: "Lime Kilns" },

  { value: "Line Heaters", label: "Line Heaters" },
  { value: "Liquid Waste Incinerators", label: "Liquid Waste Incinerators" },
  { value: "Livestock Feed Dryer", label: "Livestock Feed Dryer" },
  { value: "LPG Cooktop", label: "LPG Cooktop" },
  { value: "Marine Boiler", label: "Marine Boiler" },
  { value: "Meat Smoker", label: "Meat Smoker" },
  { value: "Medical Waste Incinerator", label: "Medical Waste Incinerator" },
  { value: "Metal Foundry Furnace", label: "Metal Foundry Furnace" },
  { value: "Military Base Generator", label: "Military Base Generator" },
  { value: "Milk Evaporator", label: "Milk Evaporator" },
  { value: "Mining Site Generator", label: "Mining Site Generator" },
  { value: "Molasses Heater", label: "Molasses Heater" },
  { value: "Natural Gas Boiler", label: "Natural Gas Boiler" },
  { value: "Natural Gas Engines", label: "Natural Gas Engines" },
  { value: "Natural Gas Heaters", label: "Natural Gas Heaters" },
  { value: "Natural Gas or Liquid-Fueled Turbines (for Electricity Generation)", label: "Natural Gas or Liquid-Fueled Turbines (for Electricity Generation)" },
  { value: "Natural Gas-Fired Boilers", label: "Natural Gas-Fired Boilers" },
  { value: "Oil Furnace", label: "Oil Furnace" },
  { value: "Oil Rig Heater", label: "Oil Rig Heater" },
  { value: "Oil-Fired Space Heaters", label: "Oil-Fired Space Heaters" },
  { value: "Package Boilers", label: "Package Boilers" },
  { value: "Paint Booth Heater", label: "Paint Booth Heater" },
  { value: "Paint Curing Oven", label: "Paint Curing Oven" },
  { value: "Paper Dryers", label: "Paper Dryers" },
  { value: "Paper Mill Boiler", label: "Paper Mill Boiler" },
  { value: "Partial Oxidation Units", label: "Partial Oxidation Units" },
  { value: "Peak Load Generator", label: "Peak Load Generator" },
  { value: "Pellet Stove", label: "Pellet Stove" },
  { value: "Pet Cremator", label: "Pet Cremator" },
  { value: "Petrochemical Crackers/Reformers", label: "Petrochemical Crackers/Reformers" },
  { value: "Petrol Stove", label: "Petrol Stove" },
  { value: "Pharmaceutical Dryer", label: "Pharmaceutical Dryer" },
  { value: "Plastic Extruder Heater", label: "Plastic Extruder Heater" },
  { value: "Polymerization Reactors with Jacket Heating (Fuel-Fired)", label: "Polymerization Reactors with Jacket Heating (Fuel-Fired)" },
  { value: "Port Facility Generator", label: "Port Facility Generator" },
  { value: "Poultry House Heater", label: "Poultry House Heater" },
  { value: "Powder Coating Oven", label: "Powder Coating Oven" },
  { value: "Printing Press Heater", label: "Printing Press Heater" },
  { value: "Process Furnaces (Refineries, Petrochemicals, Steel)", label: "Process Furnaces (Refineries, Petrochemicals, Steel)" },

  { value: "Process Heaters", label: "Process Heaters" },
  { value: "Propane Heater", label: "Propane Heater" },
  { value: "Pulp Digester", label: "Pulp Digester" },
  { value: "Pulverized Coal Boilers", label: "Pulverized Coal Boilers" },
  { value: "Pumping Station Engines (Oil & Gas, Water Pumping)", label: "Pumping Station Engines (Oil & Gas, Water Pumping)" },
  { value: "Railway Station Boiler", label: "Railway Station Boiler" },
  { value: "Reboilers (for Distillation Units)", label: "Reboilers (for Distillation Units)" },
  { value: "Reboilers for Distillation of Aromatics", label: "Reboilers for Distillation of Aromatics" },
  { value: "Reciprocating Engines (Gas/Diesel Gensets)", label: "Reciprocating Engines (Gas/Diesel Gensets)" },
  { value: "Reforming Furnaces", label: "Reforming Furnaces" },
  { value: "Regeneration Heaters", label: "Regeneration Heaters" },
  { value: "Regenerative Thermal Oxidizers (RTOs)", label: "Regenerative Thermal Oxidizers (RTOs)" },
  { value: "Reheating Furnaces (Steel Mills, Forging)", label: "Reheating Furnaces (Steel Mills, Forging)" },
  { value: "Remote Site Generator", label: "Remote Site Generator" },
  { value: "Restaurant Stove", label: "Restaurant Stove" },
  { value: "Rice Dryer", label: "Rice Dryer" },
  { value: "Rotary Dryers (Agriculture, Mining, Chemicals)", label: "Rotary Dryers (Agriculture, Mining, Chemicals)" },
  { value: "Rotary Kiln", label: "Rotary Kiln" },
  { value: "Rubber Vulcanizer", label: "Rubber Vulcanizer" },
  { value: "Seafood Boiler", label: "Seafood Boiler" },
  { value: "Shipboard Generator", label: "Shipboard Generator" },
  { value: "Sludge Incinerators", label: "Sludge Incinerators" },
  { value: "Slug Catcher Line Heaters", label: "Slug Catcher Line Heaters" },
  { value: "Smelters (Non-Ferrous Metallurgy)", label: "Smelters (Non-Ferrous Metallurgy)" },
  { value: "Smelting Furnace", label: "Smelting Furnace" },
  { value: "Space Heater", label: "Space Heater" },
  { value: "Standby Generator", label: "Standby Generator" },
  { value: "Steam Boilers for Heating", label: "Steam Boilers for Heating" },
  { value: "Steam Boilers for Power", label: "Steam Boilers for Power" },
  { value: "Steam Cracker Furnaces", label: "Steam Cracker Furnaces" },
  { value: "Steam Methane Reformers (SMRs)", label: "Steam Methane Reformers (SMRs)" },
  { value: "Steam Turbines", label: "Steam Turbines" },
  { value: "Steamer", label: "Steamer" },
  { value: "Street Vendor Grill", label: "Street Vendor Grill" },
  { value: "Sugar Dryer", label: "Sugar Dryer" },
  { value: "Sulfur Recovery Unit (SRU) Thermal Reactors", label: "Sulfur Recovery Unit (SRU) Thermal Reactors" },
  { value: "Tail Gas Treating Unit Burners", label: "Tail Gas Treating Unit Burners" },
  { value: "Tar Melter", label: "Tar Melter" },
  { value: "Tea Dryer", label: "Tea Dryer" },
  { value: "Tempering Furnace", label: "Tempering Furnace" },
  { value: "Textile Boiler", label: "Textile Boiler" },
  { value: "Textile Dryers", label: "Textile Dryers" },
  { value: "Thermal Oxidizers (for Waste Gas)", label: "Thermal Oxidizers (for Waste Gas)" },
  { value: "Thermal Oxidizers (Fuel-Assisted)", label: "Thermal Oxidizers (Fuel-Assisted)" },
  { value: "Thermal Oxidizers (VOC Control)", label: "Thermal Oxidizers (VOC Control)" },
  { value: "Turbine-driven Compressors (e.g., Pipelines)", label: "Turbine-driven Compressors (e.g., Pipelines)" },
  { value: "Vacuum Heaters", label: "Vacuum Heaters" },
  { value: "Veterinary Incinerator", label: "Veterinary Incinerator" },
  { value: "Waste Gas/Fluid Incinerators (e.g. Produced Water Treatment)", label: "Waste Gas/Fluid Incinerators (e.g. Produced Water Treatment)" },
  { value: "Wellhead Line Heaters (Natural Gas-Fired)", label: "Wellhead Line Heaters (Natural Gas-Fired)" },
  { value: "WFI (Water for Injection) Generator Boilers", label: "WFI (Water for Injection) Generator Boilers" },
  { value: "Winery Boiler", label: "Winery Boiler" },
  { value: "Wood Stove", label: "Wood Stove" }
];

export const stakeholderOptions = [
  { value: "Assembly", label: "Assembly" },
  { value: "Asset Integrity / Technical Integrity", label: "Asset Integrity / Technical Integrity" },
  { value: "Biostatistics / Statistical Programming", label: "Biostatistics / Statistical Programming" },
  { value: "Blow Molding / Extrusion Trials Unit", label: "Blow Molding / Extrusion Trials Unit" },
  { value: "Boiler Operations", label: "Boiler Operations" },
  { value: "Carbon Accounting", label: "Carbon Accounting" },
  { value: "Catalyst & Additives Handling (Petrochem Focus)", label: "Catalyst & Additives Handling (Petrochem Focus)" },
  { value: "Catalyst Management", label: "Catalyst Management" },
  { value: "Change Management", label: "Change Management" },
  { value: "Chemical Operations (Olefins, Aromatics, Polymers)", label: "Chemical Operations (Olefins, Aromatics, Polymers)" },
  { value: "Clinical Data Management (CDM)", label: "Clinical Data Management (CDM)" },
  { value: "Clinical Operations", label: "Clinical Operations" },
  { value: "Clinical Research & Development (Clinical R&D)", label: "Clinical Research & Development (Clinical R&D)" },
  { value: "Clinical Trial Management / Site Monitoring", label: "Clinical Trial Management / Site Monitoring" },
  { value: "CMC (Chemistry, Manufacturing & Controls)", label: "CMC (Chemistry, Manufacturing & Controls)" },
  { value: "Commercial / Sales / Marketing", label: "Commercial / Sales / Marketing" },
  { value: "Compliance & Audits", label: "Compliance & Audits" },
  { value: "Compliance / Legal / Regulatory Affairs", label: "Compliance / Legal / Regulatory Affairs" },
  { value: "Compounding & Blending", label: "Compounding & Blending" },
  { value: "Compressed Air Systems", label: "Compressed Air Systems" },
  { value: "Corporate Banking", label: "Corporate Banking" },
  { value: "Costing & Budgeting", label: "Costing & Budgeting" },
  { value: "Cracker Unit Operations (e.g., Steam Cracker, Naphtha Cracker)", label: "Cracker Unit Operations (e.g., Steam Cracker, Naphtha Cracker)" },
  { value: "Customer Service", label: "Customer Service" },
  { value: "Cybersecurity", label: "Cybersecurity" },
  { value: "Data Analytics", label: "Data Analytics" },
  { value: "Document Control", label: "Document Control" },
  { value: "Drilling & Completions", label: "Drilling & Completions" },
  { value: "Effluent Treatment Plant (ETP)", label: "Effluent Treatment Plant (ETP)" },
  { value: "Emergency Response", label: "Emergency Response" },
  { value: "Emissions Monitoring", label: "Emissions Monitoring" },
  { value: "Energy Management", label: "Energy Management" },
  { value: "Environmental / Sustainability", label: "Environmental / Sustainability" },
  { value: "Environmental Compliance", label: "Environmental Compliance" },
  { value: "ERP Management", label: "ERP Management" },
  { value: "Feedstock Coordination / Feedstock Planning", label: "Feedstock Coordination / Feedstock Planning" },
  { value: "Finance & Accounting", label: "Finance & Accounting" },
  { value: "Fire & Emergency Response", label: "Fire & Emergency Response" },
  { value: "Fire & Safety", label: "Fire & Safety" },
  { value: "Flare Management / Flare Systems", label: "Flare Management / Flare Systems" },
  { value: "Formulation Development (F&D)", label: "Formulation Development (F&D)" },

  { value: "Gas Processing Plant", label: "Gas Processing Plant" },
  { value: "Grid Operations", label: "Grid Operations" },
  { value: "Health, Safety & Environment (HSE / EHS)", label: "Health, Safety & Environment (HSE / EHS)" },
  { value: "Heat Treatment", label: "Heat Treatment" },
  { value: "Human Resources (HR)", label: "Human Resources (HR)" },
  { value: "HVAC Systems", label: "HVAC Systems" },
  { value: "Hydrocarbon Accounting", label: "Hydrocarbon Accounting" },
  { value: "Industrial Automation", label: "Industrial Automation" },
  { value: "Inventory Management", label: "Inventory Management" },
  { value: "IT / OT / Digitalization", label: "IT / OT / Digitalization" },
  { value: "IT Infrastructure", label: "IT Infrastructure" },
  { value: "Kaizen / Continuous Improvement", label: "Kaizen / Continuous Improvement" },
  { value: "Laboratory Services", label: "Laboratory Services" },
  { value: "LNG Operations", label: "LNG Operations" },
  { value: "Loan Processing", label: "Loan Processing" },
  { value: "Logistics & Dispatch", label: "Logistics & Dispatch" },
  { value: "Logistics & Supply Chain", label: "Logistics & Supply Chain" },
  { value: "Maintenance & Reliability", label: "Maintenance & Reliability" },
  { value: "Manufacturing / Fabrication", label: "Manufacturing / Fabrication" },
  { value: "Marine & Offshore Operations", label: "Marine & Offshore Operations" },
  { value: "Materials Science / Polymer Lab", label: "Materials Science / Polymer Lab" },
  { value: "Mechanical, Electrical, and Instrumentation (MEI)", label: "Mechanical, Electrical, and Instrumentation (MEI)" },
  { value: "Medical Affairs / Scientific Liaison", label: "Medical Affairs / Scientific Liaison" },
  { value: "Medical Records", label: "Medical Records" },
  { value: "Medical Writing / Regulatory Writing", label: "Medical Writing / Regulatory Writing" },
  { value: "Monomer Production Units", label: "Monomer Production Units" },
  { value: "Occupational Health & Safety", label: "Occupational Health & Safety" },
  { value: "Offsites & Utilities", label: "Offsites & Utilities" },
  { value: "Oil Processing Plant", label: "Oil Processing Plant" },
  { value: "Operations / Production", label: "Operations / Production" },
  { value: "Packaging", label: "Packaging" },

  { value: "Packaging Development", label: "Packaging Development" },
  { value: "Payroll & Benefits", label: "Payroll & Benefits" },
  { value: "Petroleum Economics / Planning", label: "Petroleum Economics / Planning" },
  { value: "Pharmacovigilance / Drug Safety", label: "Pharmacovigilance / Drug Safety" },
  { value: "Pharmacy Services", label: "Pharmacy Services" },
  { value: "Pipeline Operations & Integrity", label: "Pipeline Operations & Integrity" },
  { value: "Planning & Scheduling", label: "Planning & Scheduling" },
  { value: "PLC Programming", label: "PLC Programming" },
  { value: "Polymer Operations / Polymerization Units", label: "Polymer Operations / Polymerization Units" },
  { value: "Power Generation", label: "Power Generation" },
  { value: "Process Engineering", label: "Process Engineering" },
  { value: "Process Safety / Technical Safety", label: "Process Safety / Technical Safety" },
  { value: "Processing Plants", label: "Processing Plants" },
  { value: "Procurement", label: "Procurement" },
  { value: "Procurement / Materials Management", label: "Procurement / Materials Management" },
  { value: "Product Formulation / R&D / Application Testing", label: "Product Formulation / R&D / Application Testing" },
  { value: "Production Operations", label: "Production Operations" },
  { value: "Production Planning & Control", label: "Production Planning & Control" },
  { value: "Projects / Engineering / Capital Projects", label: "Projects / Engineering / Capital Projects" },
  { value: "Quality Control / Quality Assurance", label: "Quality Control / Quality Assurance" },
  { value: "R&D / Product Development", label: "R&D / Product Development" },
  { value: "Radiology Department", label: "Radiology Department" },
  { value: "Recruitment & Training", label: "Recruitment & Training" },
  { value: "Refineries Operations", label: "Refineries Operations" },
  { value: "Refining Operations / Units (e.g., CDU, FCC, Hydrocracker)", label: "Refining Operations / Units (e.g., CDU, FCC, Hydrocracker)" },
  { value: "Regulatory Affairs", label: "Regulatory Affairs" },
  { value: "Reservoir Engineering", label: "Reservoir Engineering" },
  { value: "Resin Production Operations", label: "Resin Production Operations" },
  { value: "Retail Banking", label: "Retail Banking" },
  { value: "Risk Management", label: "Risk Management" },
  { value: "SCADA / DCS Systems", label: "SCADA / DCS Systems" },
  { value: "Sewage Treatment Plant (STP)", label: "Sewage Treatment Plant (STP)" },
  { value: "Stability Testing / ICH Compliance", label: "Stability Testing / ICH Compliance" },
  { value: "Subsurface / Geoscience", label: "Subsurface / Geoscience" },
  { value: "Supply Chain & Cold Chain Logistics", label: "Supply Chain & Cold Chain Logistics" },
  { value: "Surface Coating", label: "Surface Coating" },
  { value: "Sustainability Reporting", label: "Sustainability Reporting" },
  { value: "Technical Services", label: "Technical Services" },
  { value: "Terminal Operations / Tank Farm", label: "Terminal Operations / Tank Farm" },
  { value: "Tool Room", label: "Tool Room" },
  { value: "Transmission & Distribution", label: "Transmission & Distribution" },
  { value: "Treasury Operations", label: "Treasury Operations" },
  { value: "Turnaround (TAR) / Shutdown Management", label: "Turnaround (TAR) / Shutdown Management" },
  { value: "Utilities & Energy", label: "Utilities & Energy" },
  { value: "Vendor Management", label: "Vendor Management" },
  { value: "Warehouse Management", label: "Warehouse Management" },
  { value: "Waste Management", label: "Waste Management" },
  { value: "Water Treatment", label: "Water Treatment" },
  { value: "Welding & Fabrication", label: "Welding & Fabrication" },
  { value: "Well Services / Well Intervention", label: "Well Services / Well Intervention" }
];

export const qualityControlOptions = [
  { value: "Highly Uncertain", label: "Highly Uncertain" },
  { value: "Uncertain", label: "Uncertain" },
  { value: "Fair", label: "Fair" },
  { value: "Good", label: "Good" },
  { value: "Exact", label: "Exact" },
];

// --- Fuel Type Options ---
export const fuelTypeOptions = [
  { value: "Gaseous Fuel", label: "Gaseous Fuel" },
  { value: "Bio Gaseous Fuel", label: "Bio Gaseous Fuel" },
  { value: "Liquid Fuel", label: "Liquid Fuel" },
  { value: "Bio Liquid Fuel", label: "Bio Liquid Fuel" },
  { value: "Solid Fuel", label: "Solid Fuel" },
  { value: "Biomass Fuel", label: "Biomass Fuel" },
];

// --- Fuel Names Based on Type ---
export const fuelNameOptionsByType = {
  "Gaseous Fuel": [
    { value: "Butane", label: "Butane" },
    { value: "CNG", label: "CNG" },
    { value: "LPG", label: "LPG" },
    { value: "Natural gas", label: "Natural gas" },
    { value: "Natural gas (100% mineral blend)", label: "Natural gas (100% mineral blend)" },
    { value: "LNG", label: "LNG" },
    { value: "Other petroleum gas", label: "Other petroleum gas" },
    { value: "Propane", label: "Propane" },
  ],
  "Bio Gaseous Fuel": [
    { value: "Biogas", label: "Biogas" },
    { value: "Landfill gas", label: "Landfill gas" },
  ],
  "Liquid Fuel": [
    { value: "Aviation spirit", label: "Aviation spirit" },
    { value: "Aviation turbine fuel", label: "Aviation turbine fuel" },
    { value: "Burning oil", label: "Burning oil" },
    { value: "Diesel (average biofuel blend)", label: "Diesel (average biofuel blend)" },
    { value: "Diesel (100% mineral diesel)", label: "Diesel (100% mineral diesel)" },
    { value: "Fuel oil", label: "Fuel oil" },
    { value: "Gas oil", label: "Gas oil" },
    { value: "Lubricants", label: "Lubricants" },
    { value: "Naphtha", label: "Naphtha" },
    { value: "Petrol (average biofuel blend)", label: "Petrol (average biofuel blend)" },
    { value: "Petrol (100% mineral petrol)", label: "Petrol (100% mineral petrol)" },
    { value: "Processed fuel oils - residual oil", label: "Processed fuel oils - residual oil" },
    { value: "Processed fuel oils - distillate oil", label: "Processed fuel oils - distillate oil" },
    { value: "Refinery miscellaneous", label: "Refinery miscellaneous" },
    { value: "Waste oils", label: "Waste oils" },
    { value: "Marine gas oil", label: "Marine gas oil" },
    { value: "Marine fuel oil", label: "Marine fuel oil" },
  ],
  "Bio Liquid Fuel": [
    { value: "Bioethanol", label: "Bioethanol" },
    { value: "Biodiesel ME", label: "Biodiesel ME" },
    { value: "Biomethane (compressed)", label: "Biomethane (compressed)" },
    { value: "Biodiesel ME (from used cooking oil)", label: "Biodiesel ME (from used cooking oil)" },
    { value: "Biodiesel ME (from tallow)", label: "Biodiesel ME (from tallow)" },
    { value: "Biodiesel HVO", label: "Biodiesel HVO" },
    { value: "Biopropane", label: "Biopropane" },
    { value: "Development diesel", label: "Development diesel" },
    { value: "Development petrol", label: "Development petrol" },
    { value: "Off road biodiesel", label: "Off road biodiesel" },
    { value: "Biomethane (liquified)", label: "Biomethane (liquified)" },
    { value: "Methanol (bio)", label: "Methanol (bio)" },
    { value: "Avtur (renewable)", label: "Avtur (renewable)" },
  ],
  "Solid Fuel": [
    { value: "Coal (industrial)", label: "Coal (industrial)" },
    { value: "Coal (electricity generation)", label: "Coal (electricity generation)" },
    { value: "Coal (domestic)", label: "Coal (domestic)" },
    { value: "Coking coal", label: "Coking coal" },
    { value: "Petroleum coke", label: "Petroleum coke" },
    {
      value: "Coal (electricity generation - home produced coal only)",
      label: "Coal (electricity generation - home produced coal only)",
    },
  ],
  "Biomass Fuel": [
    { value: "Wood logs", label: "Wood logs" },
    { value: "Wood chips", label: "Wood chips" },
    { value: "Wood pellets", label: "Wood pellets" },
    { value: "Grass / straw", label: "Grass / straw" },
  ],
};

// --- Fuel Consumption Units by Fuel Name ---
export const fuelUnitOptionsByName = {
  // common units (since all have these)
  default: [
    "Tonnes",
    "kg",
    "lb",
    "kwh",
    "MWh",
    "GWh",
    "Joules",
    "Gj",
    "Mj",
    "Tj",
    "Btu",
    "MMBtu",
  ],

  // extra units for specific fuels
  "Butane": ["Litres", "Gallons"],
  "CNG": ["Litres", "Gallons"],
  "Natural gas": ["m3", "ft3", "SCF", "in3"],
  "Natural gas (100% mineral blend)": ["m3", "ft3", "in3", "SCF"],
  "LPG": ["Litres", "Gallons"],
  "LNG": ["Litres", "Gallons"],
  "Other petroleum gas": ["Litres", "Gallons"],
  "Propane": ["Litres", "Gallons"],
  "Aviation spirit": ["Litres", "Gallons"],
  "Aviation turbine fuel": ["Litres", "Gallons"],
  "Burning oil": ["Litres", "Gallons"],
  "Petrol (average biofuel blend)": ["Litres", "Gallons"],
  "Diesel (average biofuel blend)": ["Litres", "Gallons"],
  "Diesel (100% mineral diesel)": ["Litres", "Gallons"],
  "Fuel oil": ["Litres", "Gallons"],
  "Gas oil": ["Litres", "Gallons"],
  "Lubricants": ["Litres", "Gallons"],
  "Naphtha": ["Litres", "Gallons"],
  "Petrol (100% mineral petrol)": ["Litres", "Gallons"],
  "Processed fuel oils - residual oil": ["Litres", "Gallons"],
  "Processed fuel oils - distillate oil": ["Litres", "Gallons"],
  "Waste oils": ["Litres", "Gallons"],
  "Marine gas oil": ["Litres", "Gallons"],
  "Marine fuel oil": ["Litres", "Gallons"],
  "Biodiesel ME": ["Litres", "Gallons"],
  "Biodiesel ME (from used cooking oil)": ["Litres", "Gallons"],
  "Biodiesel ME (from tallow)": ["Litres", "Gallons"],
  "Biodiesel HVO": ["Litres", "Gallons"],
  "Biopropane": ["Litres", "Gallons"],
  "Development diesel": ["Litres", "Gallons"],
  "Development petrol": ["Litres", "Gallons"],
  "Off road biodiesel": ["Litres", "Gallons"],
  "Methanol (bio)": ["Litres", "Gallons"],
  "Avtur (renewable)": ["Litres", "Gallons"],
  "Bioethanol": ["Litres", "Gallons"]
};