export const wasteCategoryOptions = [
  { value: "Construction", label: "Construction" },
  { value: "Refuse (General Mixed Waste/Unsorted Waste)", label: "Refuse (General Mixed Waste/Unsorted Waste)" },
  { value: "Electrical Items", label: "Electrical items" },
  { value: "Metal", label: "Metal" },
  { value: "Plastic", label: "Plastic" },
  { value: "Paper", label: "Paper" },
  { value: "Others", label: "Others" },
];

export const wasteTypeOptions = {
  Construction: [
    "Aggregates",
    "Average construction",
    "Asbestos",
    "Asphalt",
    "Bricks",
    "Concrete",
    "Insulation",
    "Metals",
    "Soils",
    "Mineral oil",
    "Plasterboard",
    "Tyres",
    "Wood"
  ].map((x) => ({ value: x, label: x })),

  "Refuse (General Mixed Waste/Unsorted Waste)": [
    "Household residual waste",
    "Organic: food and drink waste",
    "Organic: garden waste",
    "Organic: mixed food and garden waste",
    "Commercial and industrial waste (Waste generated by businesses or industrial operations)",
  ].map((x) => ({ value: x, label: x })),

  "Electrical Items": [
    "Waste Electrical and Electronic Equipment - fridges and freezers",
    "Waste Electrical and Electronic Equipment - large electrical equipments (Washing machine, Ovens, Large printers, Photocopiers, Large appliances or machinery)",
    "Waste Electrical and Electronic Equipment - mixed/unsorted electrical equipments",
    "Waste Electrical and Electronic Equipment - small electrical equipments (Phones, Chargers, Small gadgets, Electric tools or Small household electronics)",
    "Batteries (Excludes car batteries)"
  ].map((x) => ({ value: x, label: x })), // Add later if needed

  Metal: [
  "Metal: aluminium cans and foil (excl. forming)",
  "Metal: mixed cans",
  "Metal: scrap metal",
  "Metal: steel cans"
].map((x) => ({ value: x, label: x })),

Plastic: [
  "Plastics: average plastics",
  "Plastics: average plastic film",
  "Plastics: average plastic rigid",
  "Plastics: HDPE (incl. forming)",
  "Plastics: LDPE and LLDPE (incl. forming)",
  "Plastics: PET (incl. forming)",
  "Plastics: PP (incl. forming)",
  "Plastics: PS (incl. forming)",
  "Plastics: PVC (incl. forming)"
].map((x) => ({ value: x, label: x })),

Paper: [
  "Paper and board: board (Average: 78% corrugate and 22% carton board)",
  "Paper and board: mixed (Assumes 25% paper, 75% board)",
  "Paper and board: paper",
  "Mixed Paper (primarily residential)",
  "Mixed Paper (primarily from offices)"
].map((x) => ({ value: x, label: x })),

Others: [
  "Books",
  "Glass",
  "Clothing"
].map((x) => ({ value: x, label: x })),

};

// export const wasteTreatmentOptions = {
//   Aggregates: ["Recycled", "Landfill"].map((x) => ({ value: x, label: x })),

//   "Average construction": [
//     "Recycled",
//     "Incineration with energy recovery",
//     "Landfill"
//   ].map((x) => ({ value: x, label: x })),
//   Asbestos: ["Recycled", "Landfill"].map((x) => ({ value: x, label: x })),
//   Aggregates: ["Recycled", "Landfill"].map((x) => ({ value: x, label: x })),
//   oneAggregates: ["Recycled", "Landfill"].map((x) => ({ value: x, label: x })),
//   rAggregates: ["Recycled", "Landfill"].map((x) => ({ value: x, label: x })),
//   yAggregates: ["Recycled", "Landfill"].map((x) => ({ value: x, label: x })),
//   tAggregates: ["Recycled", "Landfill"].map((x) => ({ value: x, label: x })),
// dAggregates: ["Recycled", "Landfill"].map((x) => ({ value: x, label: x })),
//   fAggregates: ["Recycled", "Landfill"].map((x) => ({ value: x, label: x })),
//   yAggregates: ["Recycled", "Landfill"].map((x) => ({ value: x, label: x })),

// };

const recycledLandfill = ["Recycled", "Landfill"];
const incinerationLandfill = ["Incineration with energy recovery", "Landfill"];
const recycledIncinerationLandfill = ["Recycled","Incineration with energy recovery", "Landfill"];

export const wasteTreatmentOptions = {
  Aggregates: recycledLandfill.map(x => ({ value: x, label: x })),

  "Average construction": [
    ...recycledLandfill,
    "Incineration with energy recovery"
  ].map(x => ({ value: x, label: x })),

  Asbestos: ["Landfill"].map(x => ({ value: x, label: x })),
  Asphalt: recycledLandfill.map(x => ({ value: x, label: x })),
  Bricks: recycledLandfill.map(x => ({ value: x, label: x })),
  Concrete: recycledLandfill.map(x => ({ value: x, label: x })),
  Insulation: recycledLandfill.map(x => ({ value: x, label: x })),
  Metals: recycledLandfill.map(x => ({ value: x, label: x })),
  Soils: recycledLandfill.map(x => ({ value: x, label: x })),
  "Mineral oil":["Recycled","Incineration with energy recovery"].map(x => ({ value: x, label: x })),
  Plasterboard: recycledLandfill.map(x => ({ value: x, label: x })),
  Tyres:[...recycledLandfill,"Incineration with energy recovery"].map(x => ({ value: x, label: x })),
  Wood:[...recycledLandfill,"Incineration with energy recovery","Composting"].map(x => ({ value: x, label: x })),
  //
 "Household residual waste": incinerationLandfill.map(x => ({ value: x, label: x })),
  "Organic: food and drink waste":[...incinerationLandfill,"Composting","Anaerobic Digestion"].map(x => ({ value: x, label: x })),
  "Organic: garden waste":[...incinerationLandfill,"Composting","Anaerobic Digestion"].map(x => ({ value: x, label: x })),
  "Organic: mixed food and garden waste":[...incinerationLandfill,"Composting","Anaerobic Digestion"].map(x => ({ value: x, label: x })),
  "Commercial and industrial waste (Waste generated by businesses or industrial operations)": incinerationLandfill.map(x => ({ value: x, label: x })),
 //
  "Waste Electrical and Electronic Equipment - fridges and freezers": recycledIncinerationLandfill.map(x => ({ value: x, label: x })),
  "Waste Electrical and Electronic Equipment - large electrical equipments (Washing machine, Ovens, Large printers, Photocopiers, Large appliances or machinery)":recycledIncinerationLandfill.map(x => ({ value: x, label: x })),
  "Waste Electrical and Electronic Equipment - mixed/unsorted electrical equipments": recycledIncinerationLandfill.map(x => ({ value: x, label: x })),
  "Waste Electrical and Electronic Equipment - small electrical equipments (Phones, Chargers, Small gadgets, Electric tools or Small household electronics)": recycledIncinerationLandfill.map(x => ({ value: x, label: x })),
  "Batteries (Excludes car batteries)": recycledIncinerationLandfill.map(x => ({ value: x, label: x })),

 //
  "Metal: aluminium cans and foil (excl. forming)": recycledIncinerationLandfill.map(x => ({ value: x, label: x })),
  "Metal: mixed cans": recycledIncinerationLandfill.map(x => ({ value: x, label: x })),
  "Metal: scrap metal": recycledIncinerationLandfill.map(x => ({ value: x, label: x })),
  "Metal: steel cans": recycledIncinerationLandfill.map(x => ({ value: x, label: x })),
  //
  "Plastics: average plastics": recycledIncinerationLandfill.map(x => ({ value: x, label: x })),
  "Plastics: average plastic film": recycledIncinerationLandfill.map(x => ({ value: x, label: x })),
  "Plastics: average plastic rigid": recycledIncinerationLandfill.map(x => ({ value: x, label: x })),
  "Plastics: HDPE (incl. forming)": recycledIncinerationLandfill.map(x => ({ value: x, label: x })),
  "Plastics: LDPE and LLDPE (incl. forming)": recycledIncinerationLandfill.map(x => ({ value: x, label: x })),
  "Plastics: PET (incl. forming)": recycledIncinerationLandfill.map(x => ({ value: x, label: x })),
  "Plastics: PP (incl. forming)": recycledIncinerationLandfill.map(x => ({ value: x, label: x })),
  "Plastics: PS (incl. forming)": recycledIncinerationLandfill.map(x => ({ value: x, label: x })),
  "Plastics: PVC (incl. forming)": recycledIncinerationLandfill.map(x => ({ value: x, label: x })),
  //
  "Paper and board: board (Average: 78% corrugate and 22% carton board)":[...recycledIncinerationLandfill,"Composting"].map(x => ({ value: x, label: x })),
  "Paper and board: mixed (Assumes 25% paper, 75% board)":[...recycledIncinerationLandfill,"Composting"].map(x => ({ value: x, label: x })),
  "Paper and board: paper":[...recycledIncinerationLandfill,"Composting"].map(x => ({ value: x, label: x })),
  "Mixed Paper (primarily residential)": recycledIncinerationLandfill.map(x => ({ value: x, label: x })),
  "Mixed Paper (primarily from offices)": recycledIncinerationLandfill.map(x => ({ value: x, label: x })),
  "Books":[...recycledIncinerationLandfill,"Composting"].map(x => ({ value: x, label: x })),
  "Glass": recycledIncinerationLandfill.map(x => ({ value: x, label: x })),
  "Clothing": recycledIncinerationLandfill.map(x => ({ value: x, label: x })),
};
  