//general
export const qualityControlOptions = [
  { value: "Highly Uncertain", label: "Highly Uncertain" },
  { value: "Uncertain", label: "Uncertain" },
  { value: "Fair", label: "Fair" },
  { value: "Good", label: "Good" },
  { value: "Exact", label: "Exact" },
];


//Fugitive
// --- Stakeholder / Department Options ---
export const FugitiveAndMobileStakeholderOptions = [
  { value: "Assembly", label: "Assembly" },
  { value: "Asset Integrity / Technical Integrity", label: "Asset Integrity / Technical Integrity" },
  { value: "Biostatistics / Statistical Programming", label: "Biostatistics / Statistical Programming" },
  { value: "Blow Molding / Extrusion Trials Unit", label: "Blow Molding / Extrusion Trials Unit" },
  { value: "Boiler Operations", label: "Boiler Operations" },
  { value: "Carbon Accounting", label: "Carbon Accounting" },
  { value: "Catalyst & Additives Handling (Petrochem Focus)", label: "Catalyst & Additives Handling (Petrochem Focus)" },
  { value: "Catalyst Management", label: "Catalyst Management" },
  { value: "Change Management", label: "Change Management" },
  { value: "Chemical Operations (Olefins, Aromatics, Polymers)", label: "Chemical Operations (Olefins, Aromatics, Polymers)" },
  { value: "Clinical Data Management (CDM)", label: "Clinical Data Management (CDM)" },
  { value: "Clinical Operations", label: "Clinical Operations" },
  { value: "Clinical Research & Development (Clinical R&D)", label: "Clinical Research & Development (Clinical R&D)" },
  { value: "Clinical Trial Management / Site Monitoring", label: "Clinical Trial Management / Site Monitoring" },
  { value: "CMC (Chemistry, Manufacturing & Controls)", label: "CMC (Chemistry, Manufacturing & Controls)" },
  { value: "Commercial / Sales / Marketing", label: "Commercial / Sales / Marketing" },
  { value: "Compliance & Audits", label: "Compliance & Audits" },
  { value: "Compliance / Legal / Regulatory Affairs", label: "Compliance / Legal / Regulatory Affairs" },
  { value: "Compounding & Blending", label: "Compounding & Blending" },
  { value: "Compressed Air Systems", label: "Compressed Air Systems" },
  { value: "Corporate Banking", label: "Corporate Banking" },
  { value: "Costing & Budgeting", label: "Costing & Budgeting" },
  { value: "Cracker Unit Operations (e.g., Steam Cracker, Naphtha Cracker)", label: "Cracker Unit Operations (e.g., Steam Cracker, Naphtha Cracker)" },
  { value: "Customer Service", label: "Customer Service" },
  { value: "Cybersecurity", label: "Cybersecurity" },
  { value: "Data Analytics", label: "Data Analytics" },
  { value: "Document Control", label: "Document Control" },
  { value: "Drilling & Completions", label: "Drilling & Completions" },
  { value: "Effluent Treatment Plant (ETP)", label: "Effluent Treatment Plant (ETP)" },
  { value: "Emergency Response", label: "Emergency Response" },
  { value: "Emissions Monitoring", label: "Emissions Monitoring" },
  { value: "Energy Management", label: "Energy Management" },
  { value: "Environmental / Sustainability", label: "Environmental / Sustainability" },
  { value: "Environmental Compliance", label: "Environmental Compliance" },
  { value: "ERP Management", label: "ERP Management" },
  { value: "Feedstock Coordination / Feedstock Planning", label: "Feedstock Coordination / Feedstock Planning" },
  { value: "Finance & Accounting", label: "Finance & Accounting" },
  { value: "Fire & Emergency Response", label: "Fire & Emergency Response" },
  { value: "Fire & Safety", label: "Fire & Safety" },
  { value: "Flare Management / Flare Systems", label: "Flare Management / Flare Systems" },
  { value: "Formulation Development (F&D)", label: "Formulation Development (F&D)" },
  { value: "Gas Processing Plant", label: "Gas Processing Plant" },
  { value: "Grid Operations", label: "Grid Operations" },
  { value: "Health, Safety & Environment (HSE / EHS)", label: "Health, Safety & Environment (HSE / EHS)" },
  { value: "Heat Treatment", label: "Heat Treatment" },
  { value: "Human Resources (HR)", label: "Human Resources (HR)" },
  { value: "HVAC Systems", label: "HVAC Systems" },
  { value: "Hydrocarbon Accounting", label: "Hydrocarbon Accounting" },
  { value: "Industrial Automation", label: "Industrial Automation" },
  { value: "Inventory Management", label: "Inventory Management" },
  { value: "IT / OT / Digitalization", label: "IT / OT / Digitalization" },
  { value: "IT Infrastructure", label: "IT Infrastructure" },
  { value: "Kaizen / Continuous Improvement", label: "Kaizen / Continuous Improvement" },
  { value: "Laboratory Services", label: "Laboratory Services" },
  { value: "LNG Operations", label: "LNG Operations" },
  { value: "Loan Processing", label: "Loan Processing" },
  { value: "Logistics & Dispatch", label: "Logistics & Dispatch" },
  { value: "Logistics & Supply Chain", label: "Logistics & Supply Chain" },
  { value: "Maintenance & Reliabilit", label: "Maintenance & Reliabilit" },
  { value: "Maintenance & Reliability", label: "Maintenance & Reliability" },
  { value: "Manufacturing / Fabrication", label: "Manufacturing / Fabrication" },
  { value: "Marine & Offshore Operations", label: "Marine & Offshore Operations" },
  { value: "Materials Science / Polymer Lab", label: "Materials Science / Polymer Lab" },
  { value: "Mechanical, Electrical, and Instrumentation (MEI)", label: "Mechanical, Electrical, and Instrumentation (MEI)" },
  { value: "Medical Affairs / Scientific Liaison", label: "Medical Affairs / Scientific Liaison" },
  { value: "Medical Records", label: "Medical Records" },
  { value: "Medical Writing / Regulatory Writing", label: "Medical Writing / Regulatory Writing" },
  { value: "Monomer Production Units", label: "Monomer Production Units" },
  { value: "Occupational Health & Safety", label: "Occupational Health & Safety" },
  { value: "Offsites & Utilities", label: "Offsites & Utilities" },
  { value: "Oil Processing Plant", label: "Oil Processing Plant" },
  { value: "Operations / Production", label: "Operations / Production" },
  { value: "Packaging", label: "Packaging" },
  { value: "Packaging Development", label: "Packaging Development" },
  { value: "Payroll & Benefits", label: "Payroll & Benefits" },
  { value: "Petroleum Economics / Planning", label: "Petroleum Economics / Planning" },
  { value: "Pharmacovigilance / Drug Safety", label: "Pharmacovigilance / Drug Safety" },
  { value: "Pharmacy Services", label: "Pharmacy Services" },
  { value: "Pipeline Operations & Integrity", label: "Pipeline Operations & Integrity" },
  { value: "Planning & Scheduling", label: "Planning & Scheduling" },
  { value: "PLC Programming", label: "PLC Programming" },
  { value: "Polymer Operations / Polymerization Units", label: "Polymer Operations / Polymerization Units" },
  { value: "Power Generation", label: "Power Generation" },
  { value: "Process Engineering", label: "Process Engineering" },
  { value: "Process Safety / Technical Safety", label: "Process Safety / Technical Safety" },
  { value: "Processing Plants", label: "Processing Plants" },
  { value: "Procurement", label: "Procurement" },
  { value: "Procurement / Materials Management", label: "Procurement / Materials Management" },
  { value: "Product Formulation / R&D / Application Testing", label: "Product Formulation / R&D / Application Testing" },
  { value: "Production Operations", label: "Production Operations" },
  { value: "Production Planning & Control", label: "Production Planning & Control" },
  { value: "Projects / Engineering / Capital Projects", label: "Projects / Engineering / Capital Projects" },
  { value: "Quality Control / Quality Assurance", label: "Quality Control / Quality Assurance" },
  { value: "R&D / Product Development", label: "R&D / Product Development" },
  { value: "Radiology Department", label: "Radiology Department" },
  { value: "Recruitment & Training", label: "Recruitment & Training" },
  { value: "Refineries Operations", label: "Refineries Operations" },
  { value: "Refining Operations / Units (e.g., CDU, FCC, Hydrocracker)", label: "Refining Operations / Units (e.g., CDU, FCC, Hydrocracker)" },
  { value: "Regulatory Affairs", label: "Regulatory Affairs" },
  { value: "Reservoir Engineering", label: "Reservoir Engineering" },
  { value: "Resin Production Operations", label: "Resin Production Operations" },
  { value: "Retail Banking", label: "Retail Banking" },
  { value: "Risk Management", label: "Risk Management" },
  { value: "SCADA / DCS Systems", label: "SCADA / DCS Systems" },
  { value: "Sewage Treatment Plant (STP)", label: "Sewage Treatment Plant (STP)" },
  { value: "Stability Testing / ICH Compliance", label: "Stability Testing / ICH Compliance" },
  { value: "Subsurface / Geoscience", label: "Subsurface / Geoscience" },
  { value: "Supply Chain & Cold Chain Logistics", label: "Supply Chain & Cold Chain Logistics" },
  { value: "Surface Coating", label: "Surface Coating" },
  { value: "Sustainability Reporting", label: "Sustainability Reporting" },
  { value: "Technical Services", label: "Technical Services" },
  { value: "Terminal Operations / Tank Farm", label: "Terminal Operations / Tank Farm" },
  { value: "Tool Room", label: "Tool Room" },
  { value: "Transmission & Distribution", label: "Transmission & Distribution" },
  { value: "Treasury Operations", label: "Treasury Operations" },
  { value: "Turnaround (TAR) / Shutdown Management", label: "Turnaround (TAR) / Shutdown Management" },
  { value: "Utilities & Energy", label: "Utilities & Energy" },
  { value: "Vendor Management", label: "Vendor Management" },
  { value: "Warehouse Management", label: "Warehouse Management" },
  { value: "Waste Management", label: "Waste Management" },
  { value: "Water Treatment", label: "Water Treatment" },
  { value: "Welding & Fabrication", label: "Welding & Fabrication" },
  { value: "Well Services / Well Intervention", label: "Well Services / Well Intervention" },
];


// --- Equipment Type Options ---
export const FugitiveEquipmentTypeOptions = [
  { value: "Absorption Chillers", label: "Absorption Chillers" },
  { value: "Air Curtains", label: "Air Curtains" },
  { value: "Air Handling Units (AHUs) with refrigerants", label: "Air Handling Units (AHUs) with refrigerants" },
  { value: "Air Preheaters and Economizers (leaks from pressure reliefs or seals)", label: "Air Preheaters and Economizers (leaks from pressure reliefs or seals)" },
  { value: "Anaerobic Digesters (Biogas Plants) – methane leaks from domes and digestate handling", label: "Anaerobic Digesters (Biogas Plants) – methane leaks from domes and digestate handling" },
  { value: "Ash Handling Systems (pneumatic conveying can cause fine particulate release with trace gases)", label: "Ash Handling Systems (pneumatic conveying can cause fine particulate release with trace gases)" },
  { value: "Autoclaves / Sterilizers (steam and gas sterilization systems)", label: "Autoclaves / Sterilizers (steam and gas sterilization systems)" },
  { value: "Battery Storage Systems (Utility-Scale) – potential VOC leaks from some chemistries", label: "Battery Storage Systems (Utility-Scale) – potential VOC leaks from some chemistries" },
  { value: "Beverage Coolers", label: "Beverage Coolers" },
  { value: "Biomass Feed Systems (methane or VOCs from decomposing organic material)", label: "Biomass Feed Systems (methane or VOCs from decomposing organic material)" },
  { value: "Bioreactors / Fermenters (gas off-streams, pressure relief)", label: "Bioreactors / Fermenters (gas off-streams, pressure relief)" },
  { value: "Blast Chillers", label: "Blast Chillers" },
  { value: "Blowdown Valves / Systems", label: "Blowdown Valves / Systems" },
  { value: "Cascade Refrigeration Systems", label: "Cascade Refrigeration Systems" },
  { value: "Central AC Systems", label: "Central AC Systems" },
  { value: "Chillers", label: "Chillers" },
  { value: "Clean Agent Systems", label: "Clean Agent Systems" },
  { value: "Coal Conveyors / Feeders (dust suppression systems with VOC additives)", label: "Coal Conveyors / Feeders (dust suppression systems with VOC additives)" },
  { value: "Coal Pulverizers / Mills (dust and VOC emissions from coal handling)", label: "Coal Pulverizers / Mills (dust and VOC emissions from coal handling)" },
  { value: "Cold Storage Units", label: "Cold Storage Units" },
  { value: "Cold Storage Units / Pharmaceutical Freezers (HFC leaks)", label: "Cold Storage Units / Pharmaceutical Freezers (HFC leaks)" },
  { value: "Compressed Air Systems (with trace solvent contamination)", label: "Compressed Air Systems (with trace solvent contamination)" },
  { value: "Compressors (reciprocating & centrifugal)", label: "Compressors (reciprocating & centrifugal)" },
  { value: "Cooling Towers", label: "Cooling Towers" },
  { value: "Cooling Towers (VOC emissions from process leaks)", label: "Cooling Towers (VOC emissions from process leaks)" },
  { value: "Deep Freezers", label: "Deep Freezers" },
  { value: "Dehumidifiers", label: "Dehumidifiers" },
  { value: "Dehydrators (e.g., glycol units)", label: "Dehydrators (e.g., glycol units)" },
  { value: "Display Freezers", label: "Display Freezers" },
  { value: "Electrical Transformers (with SF₆ or insulating gases)", label: "Electrical Transformers (with SF₆ or insulating gases)" },
  { value: "Environmental Chambers / Stability Chambers (HFC emissions)", label: "Environmental Chambers / Stability Chambers (HFC emissions)" },
  { value: "Exhaust Fans", label: "Exhaust Fans" },
  { value: "Fire Extinguishers", label: "Fire Extinguishers" },
  { value: "Fire Suppression Systems", label: "Fire Suppression Systems" },
  { value: "Flanges & Pipe Connectors", label: "Flanges & Pipe Connectors" },
  { value: "Flares (unlit or inefficient combustion)", label: "Flares (unlit or inefficient combustion)" },
  { value: "Fume Hoods and Exhaust Cabinets", label: "Fume Hoods and Exhaust Cabinets" },
  { value: "Gas Chromatography Equipment (carrier gas leaks)", label: "Gas Chromatography Equipment (carrier gas leaks)" },
  { value: "Gas Flares (unlit or malfunctioning)", label: "Gas Flares (unlit or malfunctioning)" },
  { value: "Gas Insulated Switchgear (GIS) – leaks of SF₆ (sulfur hexafluoride)", label: "Gas Insulated Switchgear (GIS) – leaks of SF₆ (sulfur hexafluoride)" },
  { value: "Glove Boxes / Isolators (if not properly sealed)", label: "Glove Boxes / Isolators (if not properly sealed)" },
  { value: "Heat Exchangers (tube leaks or seal failures)", label: "Heat Exchangers (tube leaks or seal failures)" },
  { value: "Heat Pumps", label: "Heat Pumps" },
  { value: "Heat Recovery Units", label: "Heat Recovery Units" },
  { value: "HVAC Test Benches", label: "HVAC Test Benches" },
  { value: "Hydrogen Fuel Systems (in hydrogen-based energy plants – leaks from storage or pipelines)", label: "Hydrogen Fuel Systems (in hydrogen-based energy plants – leaks from storage or pipelines)" },
  { value: "Ice Cream Machines", label: "Ice Cream Machines" },
  { value: "Ice Machines", label: "Ice Machines" },
  { value: "Industrial Chillers", label: "Industrial Chillers" },
  { value: "Industrial Freezers", label: "Industrial Freezers" },
  { value: "Laboratory Freezers", label: "Laboratory Freezers" },
  { value: "Laminar Flow Cabinets (minor fugitive flows in containment areas)", label: "Laminar Flow Cabinets (minor fugitive flows in containment areas)" },
  { value: "Landfill Gas Collection Systems (in waste-to-energy plants)", label: "Landfill Gas Collection Systems (in waste-to-energy plants)" },
  { value: "Leak Detection and Repair (LDAR) Equipment", label: "Leak Detection and Repair (LDAR) Equipment" },
  { value: "Loading / Unloading Equipment", label: "Loading / Unloading Equipment" },
  { value: "Lyophilizers (Freeze Dryers)", label: "Lyophilizers (Freeze Dryers)" },
  { value: "Medical Refrigerators", label: "Medical Refrigerators" },
  { value: "Nitrogen Blanketing Systems (small leaks in tanks or vessels)", label: "Nitrogen Blanketing Systems (small leaks in tanks or vessels)" },
  { value: "Open-Ended Lines (OELs)", label: "Open-Ended Lines (OELs)" },
  { value: "Pigging Stations", label: "Pigging Stations" },
  { value: "Pipelines (gathering, transmission, distribution)", label: "Pipelines (gathering, transmission, distribution)" },
  { value: "Pneumatic Devices and Controllers", label: "Pneumatic Devices and Controllers" },
  { value: "Precision Cooling Units", label: "Precision Cooling Units" },
  { value: "Pressure Relief Devices (PRDs)", label: "Pressure Relief Devices (PRDs)" },
  { value: "Pumps (centrifugal & reciprocating)", label: "Pumps (centrifugal & reciprocating)" },
  { value: "Reactors (vessel seals and connections)", label: "Reactors (vessel seals and connections)" },
  { value: "Refrigerated Containers", label: "Refrigerated Containers" },
  { value: "Refrigerated Trucks", label: "Refrigerated Trucks" },
  { value: "Refrigerators", label: "Refrigerators" },
  { value: "Rooftop Units", label: "Rooftop Units" },
  { value: "Sample Connections / Sampling Systems", label: "Sample Connections / Sampling Systems" },
  { value: "Scrubber Waste Handling Units (sludge degassing can emit trace VOCs)", label: "Scrubber Waste Handling Units (sludge degassing can emit trace VOCs)" },
  { value: "Separators & Treaters", label: "Separators & Treaters" },
  { value: "Server Room Cooling Units", label: "Server Room Cooling Units" },
  { value: "Solar Thermal Storage Systems (leaks from molten salt or heat transfer fluids)", label: "Solar Thermal Storage Systems (leaks from molten salt or heat transfer fluids)" },
  { value: "Solvent Mixing & Dosing Systems", label: "Solvent Mixing & Dosing Systems" },
  { value: "Solvent Recovery Units", label: "Solvent Recovery Units" },
  { value: "Split ACs", label: "Split ACs" },
  { value: "Storage Tanks", label: "Storage Tanks" },
  { value: "Storage Tanks (fixed roof, floating roof, vents)", label: "Storage Tanks (fixed roof, floating roof, vents)" },
  { value: "Supermarket Display Cases", label: "Supermarket Display Cases" },
  { value: "Turbines (steam, gas, and combined cycle – seal and lubrication system leaks)", label: "Turbines (steam, gas, and combined cycle – seal and lubrication system leaks)" },
  { value: "Under-counter Refrigerators", label: "Under-counter Refrigerators" },
  { value: "Vacuum Pumps (especially in solvent-rich environments)", label: "Vacuum Pumps (especially in solvent-rich environments)" },
  { value: "Valves (especially control valves and block valves)", label: "Valves (especially control valves and block valves)" },
  { value: "Vending Machines", label: "Vending Machines" },
  { value: "VRF Systems", label: "VRF Systems" },
  { value: "Walk-in Coolers", label: "Walk-in Coolers" },
  { value: "Water Coolers", label: "Water Coolers" },
  { value: "Wellheads", label: "Wellheads" },
  { value: "Window ACs", label: "Window ACs" },
];


// --- Material / Refrigerant Options ---
export const materialRefrigerantOptions = [
  { value: "Carbon dioxide", label: "Carbon dioxide" },
  { value: "Methane", label: "Methane" },
  { value: "Nitrous oxide", label: "Nitrous oxide" },
  { value: "HFC-23", label: "HFC-23" },
  { value: "HFC-32", label: "HFC-32" },
  { value: "HFC-41", label: "HFC-41" },
  { value: "HFC-125", label: "HFC-125" },
  { value: "HFC-134", label: "HFC-134" },
  { value: "HFC-134a", label: "HFC-134a" },
  { value: "HFC-143", label: "HFC-143" },
  { value: "HFC-143a", label: "HFC-143a" },
  { value: "HFC-152a", label: "HFC-152a" },
  { value: "HFC-227ea", label: "HFC-227ea" },
  { value: "HFC-236fa", label: "HFC-236fa" },
  { value: "HFC-245fa", label: "HFC-245fa" },
  { value: "HFC-43-I0mee", label: "HFC-43-I0mee" },
  { value: "Perfluoromethane (PFC-14)", label: "Perfluoromethane (PFC-14)" },
  { value: "Perfluoroethane (PFC-116)", label: "Perfluoroethane (PFC-116)" },
  { value: "Perfluoropropane (PFC-218)", label: "Perfluoropropane (PFC-218)" },
  { value: "Perfluorocyclobutane (PFC-318)", label: "Perfluorocyclobutane (PFC-318)" },
  { value: "Perfluorobutane (PFC-3-1-10)", label: "Perfluorobutane (PFC-3-1-10)" },
  { value: "Perfluoropentane (PFC-4-1-12)", label: "Perfluoropentane (PFC-4-1-12)" },
  { value: "Perfluorohexane (PFC-5-1-14)", label: "Perfluorohexane (PFC-5-1-14)" },
  { value: "PFC-9-1-18", label: "PFC-9-1-18" },
  { value: "Perfluorocyclopropane", label: "Perfluorocyclopropane" },
  { value: "Sulphur hexafluoride (SF6)", label: "Sulphur hexafluoride (SF6)" },
  { value: "HFC-152", label: "HFC-152" },
  { value: "HFC-161", label: "HFC-161" },
  { value: "HFC-236cb", label: "HFC-236cb" },
  { value: "HFC-236ea", label: "HFC-236ea" },
  { value: "HFC-245ca", label: "HFC-245ca" },
  { value: "HFC-365mfc", label: "HFC-365mfc" },
  { value: "Nitrogen trifluoride", label: "Nitrogen trifluoride" },
  { value: "R401A", label: "R401A" },
  { value: "R401B", label: "R401B" },
  { value: "R401C", label: "R401C" },
  { value: "R402A", label: "R402A" },
  { value: "R402B", label: "R402B" },
  { value: "R403A", label: "R403A" },
  { value: "R403B", label: "R403B" },
  { value: "R404A", label: "R404A" },
  { value: "R405A", label: "R405A" },
  { value: "R406A", label: "R406A" },
  { value: "R407A", label: "R407A" },
  { value: "R407B", label: "R407B" },
  { value: "R407C", label: "R407C" },
  { value: "R407D", label: "R407D" },
  { value: "R407E", label: "R407E" },
  { value: "R407F", label: "R407F" },
  { value: "R408A", label: "R408A" },
  { value: "R409A", label: "R409A" },
  { value: "R409B", label: "R409B" },
  { value: "R410A", label: "R410A" },
  { value: "R410B", label: "R410B" },
  { value: "R411A", label: "R411A" },
  { value: "R411B", label: "R411B" },
  { value: "R412A", label: "R412A" },
  { value: "R413A", label: "R413A" },
  { value: "R414A", label: "R414A" },
  { value: "R414B", label: "R414B" },
  { value: "R415A", label: "R415A" },
  { value: "R415B", label: "R415B" },
  { value: "R416A", label: "R416A" },
  { value: "R417A", label: "R417A" },
  { value: "R417B", label: "R417B" },
  { value: "R417C", label: "R417C" },
  { value: "R418A", label: "R418A" },
  { value: "R419A", label: "R419A" },
  { value: "R419B", label: "R419B" },
  { value: "R420A", label: "R420A" },
  { value: "R421A", label: "R421A" },
  { value: "R421B", label: "R421B" },
  { value: "R422A", label: "R422A" },
  { value: "R422B", label: "R422B" },
  { value: "R422C", label: "R422C" },
  { value: "R422D", label: "R422D" },
  { value: "R422E", label: "R422E" },
  { value: "R423A", label: "R423A" },
  { value: "R424A", label: "R424A" },
  { value: "R425A", label: "R425A" },
  { value: "R426A", label: "R426A" },
  { value: "R427A", label: "R427A" },
  { value: "R428A", label: "R428A" },
  { value: "R429A", label: "R429A" },
  { value: "R430A", label: "R430A" },
  { value: "R431A", label: "R431A" },
  { value: "R432A", label: "R432A" },
  { value: "R433A", label: "R433A" },
  { value: "R433B", label: "R433B" },
  { value: "R433C", label: "R433C" },
  { value: "R434A", label: "R434A" },
  { value: "R435A", label: "R435A" },
  { value: "R436A", label: "R436A" },
  { value: "R436B", label: "R436B" },
  { value: "R437A", label: "R437A" },
  { value: "R438A", label: "R438A" },
  { value: "R439A", label: "R439A" },
  { value: "R440A", label: "R440A" },
  { value: "R441A", label: "R441A" },
  { value: "R442A", label: "R442A" },
  { value: "R443A", label: "R443A" },
  { value: "R444A", label: "R444A" },
  { value: "R445A", label: "R445A" },
  { value: "R500", label: "R500" },
  { value: "R501", label: "R501" },
  { value: "R502", label: "R502" },
  { value: "R503", label: "R503" },
  { value: "R504", label: "R504" },
  { value: "R505", label: "R505" },
  { value: "R506", label: "R506" },
  { value: "R507A", label: "R507A" },
  { value: "R508A", label: "R508A" },
  { value: "R508B", label: "R508B" },
  { value: "R509A", label: "R509A" },
  { value: "R510A", label: "R510A" },
  { value: "R511A", label: "R511A" },
  { value: "R512A", label: "R512A" },
  { value: "CFC-11/R11 = trichlorofluoromethane", label: "CFC-11/R11 = trichlorofluoromethane" },
  { value: "CFC-12/R12 = dichlorodifluoromethane", label: "CFC-12/R12 = dichlorodifluoromethane" },
  { value: "CFC-13", label: "CFC-13" },
  { value: "CFC-113", label: "CFC-113" },
  { value: "CFC-114", label: "CFC-114" },
  { value: "CFC-115", label: "CFC-115" },
  { value: "Halon-1211", label: "Halon-1211" },
  { value: "Halon-1301", label: "Halon-1301" },
  { value: "Halon-2402", label: "Halon-2402" },
  { value: "Carbon tetrachloride", label: "Carbon tetrachloride" },
  { value: "Methyl bromide", label: "Methyl bromide" },
  { value: "Methyl chloroform", label: "Methyl chloroform" },
  { value: "HCFC-22/R22 = chlorodifluoromethane", label: "HCFC-22/R22 = chlorodifluoromethane" },
  { value: "HCFC-123", label: "HCFC-123" },
  { value: "HCFC-124", label: "HCFC-124" },
  { value: "HCFC-141b", label: "HCFC-141b" },
  { value: "HCFC-142b", label: "HCFC-142b" },
  { value: "HCFC-225ca", label: "HCFC-225ca" },
  { value: "HCFC-225cb", label: "HCFC-225cb" },
  { value: "HCFC-21", label: "HCFC-21" },
  { value: "HFE-125", label: "HFE-125" },
  { value: "HFE-134", label: "HFE-134" },
  { value: "HFE-143a", label: "HFE-143a" },
  { value: "HCFE-235da2", label: "HCFE-235da2" },
  { value: "HFE-245cb2", label: "HFE-245cb2" },
  { value: "HFE-245fa2", label: "HFE-245fa2" },
  { value: "HFE-254cb2", label: "HFE-254cb2" },
  { value: "HFE-347mcc3", label: "HFE-347mcc3" },
  { value: "HFE-347pcf2", label: "HFE-347pcf2" },
  { value: "HFE-356pcc3", label: "HFE-356pcc3" },
  { value: "HFE-449sl (HFE-7100)", label: "HFE-449sl (HFE-7100)" },
  { value: "HFE-569sf2 (HFE-7200)", label: "HFE-569sf2 (HFE-7200)" },
  { value: "HFE-43-10pccc124 (H-Galden1040x)", label: "HFE-43-10pccc124 (H-Galden1040x)" },
  { value: "HFE-236ca12 (HG-10)", label: "HFE-236ca12 (HG-10)" },
  { value: "HFE-338pcc13 (HG-01)", label: "HFE-338pcc13 (HG-01)" },
  { value: "Trifluoromethyl sulphur pentafluoride", label: "Trifluoromethyl sulphur pentafluoride" },
  { value: "PFPMIE", label: "PFPMIE" },
  { value: "Dimethylether", label: "Dimethylether" },
  { value: "Methylene chloride", label: "Methylene chloride" },
  { value: "Methyl chloride", label: "Methyl chloride" },
  { value: "R290 = propane", label: "R290 = propane" },
  { value: "R600A = isobutane", label: "R600A = isobutane" },
  { value: "R600 = butane", label: "R600 = butane" },
  { value: "R601 = n-pentane", label: "R601 = n-pentane" },
  { value: "R601A = isopentane", label: "R601A = isopentane" },
  { value: "R170 = ethane", label: "R170 = ethane" },
  { value: "R1270 = propylene", label: "R1270 = propylene" },
  { value: "R1234yf*", label: "R1234yf*" },
  { value: "R1234ze*", label: "R1234ze*" },
];


// --- Quality Control Options ---
export const FugitiveQualityControlOptions = [
  { value: "Highly Uncertain", label: "Highly Uncertain" },
  { value: "Uncertain", label: "Uncertain" },
  { value: "Fair", label: "Fair" },
  { value: "Good", label: "Good" },
  { value: "Exact", label: "Exact" },
];

// --- Consumption Unit Options ---
export const consumptionUnitOptions = [{ value: "kg", label: "kg" }];

//mobile - combustion source options
// --- Vehicle Classifications ---
export const vehicleClassificationOptions = [
  { value: "By Market Segment", label: "By Market Segment" },
  { value: "By Size", label: "By Size" },
  { value: "Motorbike", label: "Motorbike" },
  { value: "Delivery Vans (Large Goods Vehicles)", label: "Delivery Vans (Large Goods Vehicles)" },
  { value: "Heavy Good Vehicles (HGVs All Diesel)", label: "Heavy Good Vehicles (HGVs All Diesel)" },
  { value: "Heavy Good Vehicles (Refrigerated HGVs All Diesel)", label: "Heavy Good Vehicles (Refrigerated HGVs All Diesel)" },
];

// --- Vehicle Types depend on classification ---
export const vehicleTypeOptionsByClassification = {
  "By Market Segment": [
    { value: "Mini - City or A-Segment Passenger Cars (600 cc - 1200 cc)", label: "Mini - City or A-Segment Passenger Cars (600 cc - 1200 cc)" },
    { value: "Supermini - Small or B-Segment Passenger Cars (1000 cc - 1600 cc)", label: "Supermini - Small or B-Segment Passenger Cars (1000 cc - 1600 cc)" },
    { value: "Lower medium - Compact or C-Segment Passenger Cars (1300 cc - 2000 cc)", label: "Lower medium - Compact or C-Segment Passenger Cars (1300 cc - 2000 cc)" },
    { value: "Upper medium - Larger or D-Segment Passenger Cars (1500cc - 2700cc)", label: "Upper medium - Larger or D-Segment Passenger Cars (1500cc - 2700cc)" },
    { value: "Executive - Large Executive or E-Segment Passenger Cars (2000cc - 3500cc+)", label: "Executive - Large Executive or E-Segment Passenger Cars (2000cc - 3500cc+)" },
    { value: "Luxury - Full size Luxury or F-Segment Premium Passenger Cars (3000cc - 6000cc)", label: "Luxury - Full size Luxury or F-Segment Premium Passenger Cars (3000cc - 6000cc)" },
    { value: "Sports - High Performance (2000cc - 4000cc+)", label: "Sports - High Performance (2000cc - 4000cc+)" },
    { value: "Dual purpose 4X4 - SUVs 4WD or AWD (1500cc - 6000cc)", label: "Dual purpose 4X4 - SUVs 4WD or AWD (1500cc - 6000cc)" },
    { value: "MPV - Multi-Purpose Vehicles / People Carriers (Highroof, Hiace,Suzuki APV, Vans etc.)  - Passenger or Transport Vehicle (1200 cc - 2000 cc)", label: "MPV - Multi-Purpose Vehicles / People Carriers (Highroof, Hiace,Suzuki APV, Vans etc.)  - Passenger or Transport Vehicle (1200 cc - 2000 cc)" },
  ],
  "By Size": [
    { value: "Small car - Petrol/LPG/CNG - up to a 1.4-litre engine. Diesel - up to a 1.7-litre engine. Others - vehicles models of a similar size (i.e. market segment A or B)", label: "Small car - Petrol/LPG/CNG - up to a 1.4-litre engine. Diesel - up to a 1.7-litre engine. Others - vehicles models of a similar size (i.e. market segment A or B)" },
    { value: "Medium car - Petrol/LPG/CNG - from 1.4-litre to 2.0-litre engine. Diesel - from 1.7-litre to 2.0-litre engine. Others - vehicles models of a similar size (i.e. generally market segment C)", label: "Medium car - Petrol/LPG/CNG - from 1.4-litre to 2.0-litre engine. Diesel - from 1.7-litre to 2.0-litre engine. Others - vehicles models of a similar size (i.e. generally market segment C)" },
    { value: "Large car - Petrol/LPG/CNG - 2.0-litre engine (+) . Diesel - 2.0-litre engine (+). Others - vehicles models of a similar size (i.e. generally market segment D and above)", label: "Large car - Petrol/LPG/CNG - 2.0-litre engine (+) . Diesel - 2.0-litre engine (+). Others - vehicles models of a similar size (i.e. generally market segment D and above)" },
    { value: "Average car - Unknown engine size.", label: "Average car - Unknown engine size." },
  ],
  "Motorbike": [
    { value: "Small", label: "Small" },
    { value: "Medium", label: "Medium" },
    { value: "Large", label: "Large" },
    { value: "Average", label: "Average" },
  ],
  "Delivery Vans (Large Goods Vehicles)": [
    { value: "Class I (up to 1.305 tonnes)", label: "Class I (up to 1.305 tonnes)" },
    { value: "Class II (1.305 to 1.74 tonnes)", label: "Class II (1.305 to 1.74 tonnes)" },
    { value: "Class III (1.74 to 3.5 tonnes)", label: "Class III (1.74 to 3.5 tonnes)" },
    { value: "Average (up to 3.5 tonnes)", label: "Average (up to 3.5 tonnes)" },
  ],
  "Heavy Good Vehicles (HGVs All Diesel)": [
    { value: "Rigid (>3.5 - 7.5 tonnes)", label: "Rigid (>3.5 - 7.5 tonnes)" },
    { value: "Rigid (>7.5 - 17 tonnes)", label: "Rigid (>7.5 - 17 tonnes)" },
    { value: "Rigid (>17 tonnes)", label: "Rigid (>17 tonnes)" },
    { value: "All rigids", label: "All rigids" },
    { value: "Articulated (>3.5 - 33 tonnes)", label: "Articulated (>3.5 - 33 tonnes)" },
    { value: "Articulated (>33 tonnes)", label: "Articulated (>33 tonnes)" },
    { value: "All artics", label: "All artics" },
    { value: "All HGVs", label: "All HGVs" },
  ],
  "Heavy Good Vehicles (Refrigerated HGVs All Diesel)": [
    { value: "Rigid (>3.5 - 7.5 tonnes)", label: "Rigid (>3.5 - 7.5 tonnes)" },
    { value: "Rigid (>7.5 - 17 tonnes)", label: "Rigid (>7.5 - 17 tonnes)" },
    { value: "Rigid (>17 tonnes)", label: "Rigid (>17 tonnes)" },
    { value: "All rigids", label: "All rigids" },
    { value: "Articulated (>3.5 - 33 tonnes)", label: "Articulated (>3.5 - 33 tonnes)" },
    { value: "Articulated (>33 tonnes)", label: "Articulated (>33 tonnes)" },
    { value: "All artics", label: "All artics" },
    { value: "All HGVs", label: "All HGVs" },
  ],
};

// --- Common Fuel Options ---
const commonFuelOptions = [
  { value: "Diesel", label: "Diesel" },
  { value: "Petrol", label: "Petrol" },
  { value: "Unknown", label: "Unknown" },
  { value: "Plug-in Hybrid Electric Vehicle", label: "Plug-in Hybrid Electric Vehicle" },
  { value: "CNG (Compressed Natural Gas)", label: "CNG (Compressed Natural Gas)" },
  { value: "LNG (Liquefied Natural Gas)", label: "LNG (Liquefied Natural Gas)" },
  { value: "LPG (Liquefied Petroleum Gas)", label: "LPG (Liquefied Petroleum Gas)" },
  { value: "Bio Diesel", label: "Bio Diesel" },
  { value: "Bio Ethanol", label: "Bio Ethanol" },
];

// --- Fuel Name depends on Vehicle Type ---
export const fuelNameOptionsByClassification = {
  "Motorbike": [{ value: "Petrol", label: "Petrol" }],

  "Heavy Good Vehicles (HGVs All Diesel)": [{ value: "Diesel", label: "Diesel" }],

  "Heavy Good Vehicles (Refrigerated HGVs All Diesel)": [{ value: "Diesel", label: "Diesel" }],

  "By Market Segment": commonFuelOptions,

  "Delivery Vans (Large Goods Vehicles)": commonFuelOptions,

  "By Size": [
    ...commonFuelOptions,
    { value: "Hybrid", label: "Hybrid" },
  ],
};

// --- Distance Unit Options ---
export const distanceUnitOptions = [
  { value: "km", label: "Kilometers (km)" },
  { value: "miles", label: "Miles" },
];

// --- Weight Loaded Options ---
export const weightLoadedOptions = [
  { value: "0%", label: "0%" },
  { value: "50%", label: "50%" },
  { value: "100%", label: "100%" },
  { value: "Average", label: "Average" },
];

// --- Quality Control (same as stationary form) ---
export const MobileQualityControlOptions = [
  { value: "Measured", label: "Measured" },
  { value: "Estimated", label: "Estimated" },
  { value: "Calculated", label: "Calculated" },
];


//Process emmissions options
// ----- options.js -----

export const stakeholderDepartmentOptions = [
  { value: "Assembly", label: "Assembly" },
  { value: "Asset Integrity / Technical Integrity", label: "Asset Integrity / Technical Integrity" },
  { value: "Biostatistics / Statistical Programming", label: "Biostatistics / Statistical Programming" },
  { value: "Blow Molding / Extrusion Trials Unit", label: "Blow Molding / Extrusion Trials Unit" },
  { value: "Boiler Operations", label: "Boiler Operations" },
  { value: "Carbon Accounting", label: "Carbon Accounting" },
  { value: "Catalyst & Additives Handling (Petrochem Focus)", label: "Catalyst & Additives Handling (Petrochem Focus)" },
  { value: "Catalyst Management", label: "Catalyst Management" },
  { value: "Change Management", label: "Change Management" },
  { value: "Chemical Operations (Olefins, Aromatics, Polymers)", label: "Chemical Operations (Olefins, Aromatics, Polymers)" },
  { value: "Clinical Data Management (CDM)", label: "Clinical Data Management (CDM)" },
  { value: "Clinical Operations", label: "Clinical Operations" },
  { value: "Clinical Research & Development (Clinical R&D)", label: "Clinical Research & Development (Clinical R&D)" },
  { value: "Clinical Trial Management / Site Monitoring", label: "Clinical Trial Management / Site Monitoring" },
  { value: "CMC (Chemistry, Manufacturing & Controls)", label: "CMC (Chemistry, Manufacturing & Controls)" },
  { value: "Commercial / Sales / Marketing", label: "Commercial / Sales / Marketing" },
  { value: "Compliance & Audits", label: "Compliance & Audits" },
  { value: "Compliance / Legal / Regulatory Affairs", label: "Compliance / Legal / Regulatory Affairs" },
  { value: "Compounding & Blending", label: "Compounding & Blending" },
  { value: "Compressed Air Systems", label: "Compressed Air Systems" },
  { value: "Corporate Banking", label: "Corporate Banking" },
  { value: "Costing & Budgeting", label: "Costing & Budgeting" },
  { value: "Cracker Unit Operations (e.g., Steam Cracker, Naphtha Cracker)", label: "Cracker Unit Operations (e.g., Steam Cracker, Naphtha Cracker)" },
  { value: "Customer Service", label: "Customer Service" },
  { value: "Cybersecurity", label: "Cybersecurity" },
  { value: "Data Analytics", label: "Data Analytics" },
  { value: "Document Control", label: "Document Control" },
  { value: "Drilling & Completions", label: "Drilling & Completions" },
  { value: "Effluent Treatment Plant (ETP)", label: "Effluent Treatment Plant (ETP)" },
  { value: "Emergency Response", label: "Emergency Response" },
  { value: "Emissions Monitoring", label: "Emissions Monitoring" },
  { value: "Energy Management", label: "Energy Management" },
  { value: "Environmental / Sustainability", label: "Environmental / Sustainability" },
  { value: "Environmental Compliance", label: "Environmental Compliance" },
  { value: "ERP Management", label: "ERP Management" },
  { value: "Feedstock Coordination / Feedstock Planning", label: "Feedstock Coordination / Feedstock Planning" },
  { value: "Finance & Accounting", label: "Finance & Accounting" },
  { value: "Fire & Emergency Response", label: "Fire & Emergency Response" },
  { value: "Fire & Safety", label: "Fire & Safety" },
  { value: "Flare Management / Flare Systems", label: "Flare Management / Flare Systems" },
  { value: "Formulation Development (F&D)", label: "Formulation Development (F&D)" },
  { value: "Gas Processing Plant", label: "Gas Processing Plant" },
  { value: "Grid Operations", label: "Grid Operations" },
  { value: "Health, Safety & Environment (HSE / EHS)", label: "Health, Safety & Environment (HSE / EHS)" },
  { value: "Heat Treatment", label: "Heat Treatment" },
  { value: "Human Resources (HR)", label: "Human Resources (HR)" },
  { value: "HVAC Systems", label: "HVAC Systems" },
  { value: "Hydrocarbon Accounting", label: "Hydrocarbon Accounting" },
  { value: "Industrial Automation", label: "Industrial Automation" },
  { value: "Inventory Management", label: "Inventory Management" },
  { value: "IT / OT / Digitalization", label: "IT / OT / Digitalization" },
  { value: "IT Infrastructure", label: "IT Infrastructure" },
  { value: "Kaizen / Continuous Improvement", label: "Kaizen / Continuous Improvement" },
  { value: "Laboratory Services", label: "Laboratory Services" },
  { value: "LNG Operations", label: "LNG Operations" },
  { value: "Loan Processing", label: "Loan Processing" },
  { value: "Logistics & Dispatch", label: "Logistics & Dispatch" },
  { value: "Logistics & Supply Chain", label: "Logistics & Supply Chain" },
  { value: "Maintenance & Reliabilit", label: "Maintenance & Reliabilit" },
  { value: "Maintenance & Reliability", label: "Maintenance & Reliability" },
  { value: "Manufacturing / Fabrication", label: "Manufacturing / Fabrication" },
  { value: "Marine & Offshore Operations", label: "Marine & Offshore Operations" },
  { value: "Materials Science / Polymer Lab", label: "Materials Science / Polymer Lab" },
  { value: "Mechanical, Electrical, and Instrumentation (MEI)", label: "Mechanical, Electrical, and Instrumentation (MEI)" },
  { value: "Medical Affairs / Scientific Liaison", label: "Medical Affairs / Scientific Liaison" },
  { value: "Medical Records", label: "Medical Records" },
  { value: "Medical Writing / Regulatory Writing", label: "Medical Writing / Regulatory Writing" },
  { value: "Monomer Production Units", label: "Monomer Production Units" },
  { value: "Occupational Health & Safety", label: "Occupational Health & Safety" },
  { value: "Offsites & Utilities", label: "Offsites & Utilities" },
  { value: "Oil Processing Plant", label: "Oil Processing Plant" },
  { value: "Operations / Production", label: "Operations / Production" },
  { value: "Packaging", label: "Packaging" },
  { value: "Packaging Development", label: "Packaging Development" },
  { value: "Payroll & Benefits", label: "Payroll & Benefits" },
  { value: "Petroleum Economics / Planning", label: "Petroleum Economics / Planning" },
  { value: "Pharmacovigilance / Drug Safety", label: "Pharmacovigilance / Drug Safety" },
  { value: "Pharmacy Services", label: "Pharmacy Services" },
  { value: "Pipeline Operations & Integrity", label: "Pipeline Operations & Integrity" },
  { value: "Planning & Scheduling", label: "Planning & Scheduling" },
  { value: "PLC Programming", label: "PLC Programming" },
  { value: "Polymer Operations / Polymerization Units", label: "Polymer Operations / Polymerization Units" },
  { value: "Power Generation", label: "Power Generation" },
  { value: "Process Engineering", label: "Process Engineering" },
  { value: "Process Safety / Technical Safety", label: "Process Safety / Technical Safety" },
  { value: "Processing Plants", label: "Processing Plants" },
  { value: "Procurement", label: "Procurement" },
  { value: "Procurement / Materials Management", label: "Procurement / Materials Management" },
  { value: "Product Formulation / R&D / Application Testing", label: "Product Formulation / R&D / Application Testing" },
  { value: "Production Operations", label: "Production Operations" },
  { value: "Production Planning & Control", label: "Production Planning & Control" },
  { value: "Projects / Engineering / Capital Projects", label: "Projects / Engineering / Capital Projects" },
  { value: "Quality Control / Quality Assurance", label: "Quality Control / Quality Assurance" },
  { value: "R&D / Product Development", label: "R&D / Product Development" },
  { value: "Radiology Department", label: "Radiology Department" },
  { value: "Recruitment & Training", label: "Recruitment & Training" },
  { value: "Refineries Operations", label: "Refineries Operations" },
  { value: "Refining Operations / Units (e.g., CDU, FCC, Hydrocracker)", label: "Refining Operations / Units (e.g., CDU, FCC, Hydrocracker)" },
  { value: "Regulatory Affairs", label: "Regulatory Affairs" },
  { value: "Reservoir Engineering", label: "Reservoir Engineering" },
  { value: "Resin Production Operations", label: "Resin Production Operations" },
  { value: "Retail Banking", label: "Retail Banking" },
  { value: "Risk Management", label: "Risk Management" },
  { value: "SCADA / DCS Systems", label: "SCADA / DCS Systems" },
  { value: "Sewage Treatment Plant (STP)", label: "Sewage Treatment Plant (STP)" },
  { value: "Stability Testing / ICH Compliance", label: "Stability Testing / ICH Compliance" },
  { value: "Subsurface / Geoscience", label: "Subsurface / Geoscience" },
  { value: "Supply Chain & Cold Chain Logistics", label: "Supply Chain & Cold Chain Logistics" },
  { value: "Surface Coating", label: "Surface Coating" },
  { value: "Sustainability Reporting", label: "Sustainability Reporting" },
  { value: "Technical Services", label: "Technical Services" },
  { value: "Terminal Operations / Tank Farm", label: "Terminal Operations / Tank Farm" },
  { value: "Tool Room", label: "Tool Room" },
  { value: "Transmission & Distribution", label: "Transmission & Distribution" },
  { value: "Treasury Operations", label: "Treasury Operations" },
  { value: "Turnaround (TAR) / Shutdown Management", label: "Turnaround (TAR) / Shutdown Management" },
  { value: "Utilities & Energy", label: "Utilities & Energy" },
  { value: "Vendor Management", label: "Vendor Management" },
  { value: "Warehouse Management", label: "Warehouse Management" },
  { value: "Waste Management", label: "Waste Management" },
  { value: "Water Treatment", label: "Water Treatment" },
  { value: "Welding & Fabrication", label: "Welding & Fabrication" },
  { value: "Well Services / Well Intervention", label: "Well Services / Well Intervention" }
];

export const activityTypeOptions = [
  { value: "Cement production (CO₂ from calcination)", label: "Cement production (CO₂ from calcination)" },
  { value: "Lime production", label: "Lime production" },
  { value: "Aluminum smelting (PFCs)", label: "Aluminum smelting (PFCs)" },
  { value: "Glass manufacturing", label: "Glass manufacturing" },
  { value: "Iron and steel production (CO₂ from reduction of iron ore)", label: "Iron and steel production (CO₂ from reduction of iron ore)" },
  { value: "Soda ash production", label: "Soda ash production" },
  { value: "Hydrogen production (from natural gas reforming)", label: "Hydrogen production (from natural gas reforming)" },
  { value: "Carbide production", label: "Carbide production" },
  { value: "Titanium dioxide production", label: "Titanium dioxide production" },
  { value: "Ethylene production (cracking process)", label: "Ethylene production (cracking process)" },
  { value: "Solvent use in paints and coatings", label: "Solvent use in paints and coatings" },
  { value: "Dry cleaning operations", label: "Dry cleaning operations" },
  { value: "Printing operations (ink solvents)", label: "Printing operations (ink solvents)" },
  { value: "Adhesive and sealant application", label: "Adhesive and sealant application" },
  { value: "Surface coating and finishing", label: "Surface coating and finishing" },
  { value: "Asphalt paving and roofing", label: "Asphalt paving and roofing" },
  { value: "Fuel dispensing at service stations", label: "Fuel dispensing at service stations" },
  { value: "Industrial cleaning agents", label: "Industrial cleaning agents" },
  { value: "Nitric acid production (N₂O)", label: "Nitric acid production (N₂O)" },
  { value: "Adipic acid production (N₂O)", label: "Adipic acid production (N₂O)" },
  { value: "Magnesium production (SF₆)", label: "Magnesium production (SF₆)" },
  { value: "Silicon production", label: "Silicon production" },
  { value: "Ferroalloy production", label: "Ferroalloy production" },
  { value: "Ammonia production", label: "Ammonia production" },
  { value: "Urea production", label: "Urea production" },
  { value: "Methanol production", label: "Methanol production" },
  { value: "Phosphoric acid production", label: "Phosphoric acid production" },
  { value: "Chlor-alkali production (CO₂ and Cl₂)", label: "Chlor-alkali production (CO₂ and Cl₂)" },
  { value: "Hydrogen production (SMR – Steam Methane Reforming)", label: "Hydrogen production (SMR – Steam Methane Reforming)" },
  { value: "Catalytic cracking / reforming units", label: "Catalytic cracking / reforming units" },
  { value: "Amine-based gas sweetening (acid gas removal)", label: "Amine-based gas sweetening (acid gas removal)" },
  { value: "Sulfur recovery units (Claus process)", label: "Sulfur recovery units (Claus process)" },
  { value: "Flue gas treatment (scrubbers, regeneration)", label: "Flue gas treatment (scrubbers, regeneration)" },
  { value: "Natural gas dehydration (glycol regeneration)", label: "Natural gas dehydration (glycol regeneration)" },
  { value: "Isomerization and alkylation processes", label: "Isomerization and alkylation processes" },
  { value: "Coke calcination (in delayed coking)", label: "Coke calcination (in delayed coking)" },
  { value: "Steam stripping / stripping towers", label: "Steam stripping / stripping towers" },
  { value: "Ethylene and Propylene production (via steam cracking)", label: "Ethylene and Propylene production (via steam cracking)" },
  { value: "Methanol synthesis (from natural gas reforming)", label: "Methanol synthesis (from natural gas reforming)" },
  { value: "Ammonia production (via Haber-Bosch process)", label: "Ammonia production (via Haber-Bosch process)" },
  { value: "Nitric acid production", label: "Nitric acid production" },
  { value: "Adipic acid production", label: "Adipic acid production" },
  { value: "Carbon black manufacturing", label: "Carbon black manufacturing" },
  { value: "Formaldehyde production", label: "Formaldehyde production" },
  { value: "Vinyl chloride monomer (VCM) production", label: "Vinyl chloride monomer (VCM) production" },
  { value: "Terephthalic acid production (used in PET plastics)", label: "Terephthalic acid production (used in PET plastics)" },
  { value: "Acrylonitrile production", label: "Acrylonitrile production" },
  { value: "Phthalic anhydride production", label: "Phthalic anhydride production" },
  { value: "Polyurethane precursor manufacturing (e.g., MDI, TDI)", label: "Polyurethane precursor manufacturing (e.g., MDI, TDI)" },
  { value: "Ethylene oxide production", label: "Ethylene oxide production" },
  { value: "Caprolactam production (used in nylon)", label: "Caprolactam production (used in nylon)" },
  { value: "Synthetic rubber production (e.g., SBR, BR)", label: "Synthetic rubber production (e.g., SBR, BR)" },
  { value: "solvent recovery and distillation systems", label: "solvent recovery and distillation systems" },
  { value: "active pharmaceutical ingredient (API) synthesis reactions", label: "active pharmaceutical ingredient (API) synthesis reactions" },
  { value: "fermentation processes (e.g., antibiotics, insulin, enzymes)", label: "fermentation processes (e.g., antibiotics, insulin, enzymes)" },
  { value: "chemical neutralization reactions", label: "chemical neutralization reactions" },
  { value: "pH adjustment processes (e.g., acid/base reactions with carbonates)", label: "pH adjustment processes (e.g., acid/base reactions with carbonates)" },
  { value: "crystallization and recrystallization steps", label: "crystallization and recrystallization steps" },
  { value: "freeze-drying (lyophilization) processes", label: "freeze-drying (lyophilization) processes" },
  { value: "clean-in-place (CIP) and sterilize-in-place (SIP) systems (chemical agents reacting and releasing gas)", label: "clean-in-place (CIP) and sterilize-in-place (SIP) systems (chemical agents reacting and releasing gas)" },
  { value: "effluent treatment processes (e.g., aerobic/anaerobic biological oxidation)", label: "effluent treatment processes (e.g., aerobic/anaerobic biological oxidation)" },
  { value: "exothermic chemical coupling or synthesis reactions (e.g., peptide synthesis)", label: "exothermic chemical coupling or synthesis reactions (e.g., peptide synthesis)" },
  { value: "sterilant or propellant preparation (e.g., EO, isopropyl alcohol)", label: "sterilant or propellant preparation (e.g., EO, isopropyl alcohol)" },
  { value: "buffer preparation (if involving carbonates or bicarbonates)", label: "buffer preparation (if involving carbonates or bicarbonates)" },
  { value: "high-shear granulation processes involving carbonates", label: "high-shear granulation processes involving carbonates" },
  { value: "tablet coating or drying (with heat-induced chemical reactions)", label: "tablet coating or drying (with heat-induced chemical reactions)" },
  { value: "diagnostic reagent formulation processes", label: "diagnostic reagent formulation processes" },
  { value: "lime-based flue gas desulfurization (FGD) units in coal power plants", label: "lime-based flue gas desulfurization (FGD) units in coal power plants" },
  { value: "carbon capture and storage (CCS) processes (e.g., amine regeneration step)", label: "carbon capture and storage (CCS) processes (e.g., amine regeneration step)" },
  { value: "chemical looping processes in clean coal technologies", label: "chemical looping processes in clean coal technologies" },
  { value: "biomass gasification (excluding combustion)", label: "biomass gasification (excluding combustion)" },
  { value: "anaerobic digestion (methane is converted to CO₂ if flared/oxidized during biogas handling)", label: "anaerobic digestion (methane is converted to CO₂ if flared/oxidized during biogas handling)" },
  { value: "electrolysis-based hydrogen generation (if powered by fossil energy)", label: "electrolysis-based hydrogen generation (if powered by fossil energy)" },
  { value: "battery recycling and chemical recovery processes (e.g., lithium-ion battery facilities)", label: "battery recycling and chemical recovery processes (e.g., lithium-ion battery facilities)" },
  { value: "thermochemical energy storage systems (e.g., molten salt reactions)", label: "thermochemical energy storage systems (e.g., molten salt reactions)" },
  { value: "waste incineration with chemical additives or catalysts", label: "waste incineration with chemical additives or catalysts" },
  { value: "geothermal fluid degassing (natural release of CO₂ from underground reservoirs)", label: "geothermal fluid degassing (natural release of CO₂ from underground reservoirs)" },
  { value: "mineral carbonation in carbon-negative energy systems", label: "mineral carbonation in carbon-negative energy systems" },
  { value: "chemical reactions in concentrated solar thermal systems (heat transfer fluids degradation)", label: "chemical reactions in concentrated solar thermal systems (heat transfer fluids degradation)" },
  { value: "fly ash or bottom ash treatment and neutralization (lime or acid reactions)", label: "fly ash or bottom ash treatment and neutralization (lime or acid reactions)" },
  { value: "water treatment plants (e.g., degassing of dissolved gases in boiler feedwater prep)", label: "water treatment plants (e.g., degassing of dissolved gases in boiler feedwater prep)" },
  { value: "synthetic fuel (e-fuel) production processes (non-combustion steps)", label: "synthetic fuel (e-fuel) production processes (non-combustion steps)" },
  { value: "Acid Gas Removal / Sweetening", label: "Acid Gas Removal / Sweetening" },
  { value: "Sulphur Recovery Units (Claus Process)", label: "Sulphur Recovery Units (Claus Process)" },
  { value: "Hydrogen Production (Steam Methane Reforming, SMR)", label: "Hydrogen Production (Steam Methane Reforming, SMR)" },
  { value: "Catalytic & Thermal Cracking", label: "Catalytic & Thermal Cracking" },
  { value: "Coke Production from Residuum", label: "Coke Production from Residuum" },
  { value: "Carbonate Treatment in Drilling Muds", label: "Carbonate Treatment in Drilling Muds" },
  { value: "Flare Gas Stabilization", label: "Flare Gas Stabilization" },
  { value: "Catalyst Regeneration (FCC Units)", label: "Catalyst Regeneration (FCC Units)" },
  { value: "Hydrotreating / Hydrodesulfurization (HDS)", label: "Hydrotreating / Hydrodesulfurization (HDS)" },
  { value: "Alkylation and Isomerization Units", label: "Alkylation and Isomerization Units" },
  { value: "Calcination in Catalyst Preparation / Regeneration", label: "Calcination in Catalyst Preparation / Regeneration" },
  { value: "Coke Calcination (Anode-grade Coke)", label: "Coke Calcination (Anode-grade Coke)" },
  { value: "Acid Gas Removal (Amine or Selexol)", label: "Acid Gas Removal (Amine or Selexol)" },
  { value: "Dehydration (Glycol Regeneration)", label: "Dehydration (Glycol Regeneration)" },
  { value: "LNG Liquefaction / Regasification (Chemical Side)", label: "LNG Liquefaction / Regasification (Chemical Side)" },
  { value: "Carbonate Removal in CO₂ Capture Units (Amine / Solvent-based)", label: "Carbonate Removal in CO₂ Capture Units (Amine / Solvent-based)" },
  { value: "Coal Carbonization / Coking", label: "Coal Carbonization / Coking" },
  { value: "Coke Calcining / Sintering", label: "Coke Calcining / Sintering" },
  { value: "Coal Gasification / Liquefaction", label: "Coal Gasification / Liquefaction" },
  { value: "Limestone / Dolomite Use in Flue Gas Desulphurization (FGD)", label: "Limestone / Dolomite Use in Flue Gas Desulphurization (FGD)" },
  { value: "Carbonate Decomposition in Fluidized Bed Boilers", label: "Carbonate Decomposition in Fluidized Bed Boilers" },
  { value: "CO₂ Capture Solvent Regeneration (Amine Scrubbing)", label: "CO₂ Capture Solvent Regeneration (Amine Scrubbing)" },
  { value: "Fuel Cell Electrochemical Processes (Reforming Fuel Cells)", label: "Fuel Cell Electrochemical Processes (Reforming Fuel Cells)" },
  { value: "Biomass Gasification or Pyrolysis", label: "Biomass Gasification or Pyrolysis" },
  { value: "Bioethanol Fermentation", label: "Bioethanol Fermentation" },
  { value: "Biodiesel Transesterification", label: "Biodiesel Transesterification" },
  { value: "Hydrogen from Electrolysis (if carbonates used)", label: "Hydrogen from Electrolysis (if carbonates used)" },
  { value: "Renewable Methane Reforming / Biomethane Upgrading", label: "Renewable Methane Reforming / Biomethane Upgrading" },
  { value: "Carbonate / Bicarbonate Neutralization in API Synthesis", label: "Carbonate / Bicarbonate Neutralization in API Synthesis" },
  { value: "Fermentation-based Production of Antibiotics, Vitamins, Enzymes", label: "Fermentation-based Production of Antibiotics, Vitamins, Enzymes" },
  { value: "CO₂ Use in Reaction Media or Extraction Systems", label: "CO₂ Use in Reaction Media or Extraction Systems" },
  { value: "Neutralization or Buffer Preparation Using Carbonates", label: "Neutralization or Buffer Preparation Using Carbonates" },
  { value: "Lyophilization or Freeze-Drying Using CO₂ Refrigerants", label: "Lyophilization or Freeze-Drying Using CO₂ Refrigerants" },
  { value: "Anaerobic Wastewater or Biowaste Treatment (On-site)", label: "Anaerobic Wastewater or Biowaste Treatment (On-site)" },
  { value: "On-site CO₂ Capture/Release in Chromatography Columns", label: "On-site CO₂ Capture/Release in Chromatography Columns" },
  { value: "Use of Nitrous Oxide in Sterilization or Anaesthesia", label: "Use of Nitrous Oxide in Sterilization or Anaesthesia" },
  { value: "Catalyst Regeneration with Carbonates or Acids", label: "Catalyst Regeneration with Carbonates or Acids" },
  { value: "Neutralization of Waste Streams (Carbonate Reactions)", label: "Neutralization of Waste Streams (Carbonate Reactions)" },
  { value: "Steam Cracking of Naphtha / Ethane", label: "Steam Cracking of Naphtha / Ethane" },
  { value: "Ethylene Oxide / Ethylene Glycol Production", label: "Ethylene Oxide / Ethylene Glycol Production" },
  { value: "Ammonia / Urea Production", label: "Ammonia / Urea Production" },
  { value: "Methanol Synthesis", label: "Methanol Synthesis" },
  { value: "Hydrogenation / Hydrocracking Units", label: "Hydrogenation / Hydrocracking Units" },
  { value: "Aromatics Production (Benzene, Toluene, Xylene)", label: "Aromatics Production (Benzene, Toluene, Xylene)" },
  { value: "Polymerization Processes (Polyethylene, Polypropylene, PVC)", label: "Polymerization Processes (Polyethylene, Polypropylene, PVC)" },
  { value: "CO₂ Stripping in Solvent Recovery / Purification", label: "CO₂ Stripping in Solvent Recovery / Purification" },
  { value: "Catalyst Calcination / Preparation", label: "Catalyst Calcination / Preparation" },
  { value: "Anaerobic Treatment of High-COD Waste Streams", label: "Anaerobic Treatment of High-COD Waste Streams" },
  { value: "Carbonate / Lime Use in Flue Gas Desulfurization (FGD)", label: "Carbonate / Lime Use in Flue Gas Desulfurization (FGD)" },
  { value: "CO₂ Capture Solvent Regeneration (Post-combustion Capture)", label: "CO₂ Capture Solvent Regeneration (Post-combustion Capture)" },
  { value: "Coking / Carbonization in Solid Fuel Power Plants", label: "Coking / Carbonization in Solid Fuel Power Plants" },
  { value: "Biomass Gasification or Pyrolysis for Power Generation", label: "Biomass Gasification or Pyrolysis for Power Generation" },
  { value: "Hydrogen Production (for Fuel Cell or IGCC plants)", label: "Hydrogen Production (for Fuel Cell or IGCC plants)" },
  { value: "Electrolytic Hydrogen Production (with Carbonates in Electrolyzer)", label: "Electrolytic Hydrogen Production (with Carbonates in Electrolyzer)" },
  { value: "CO₂ Venting from Supercritical CO₂ Power Cycles", label: "CO₂ Venting from Supercritical CO₂ Power Cycles" },
  { value: "Anaerobic Wastewater Treatment (Power Plant Effluent)", label: "Anaerobic Wastewater Treatment (Power Plant Effluent)" },
  { value: "Fuel Cell-based Power Generation (Reforming NG)", label: "Fuel Cell-based Power Generation (Reforming NG)" }
];

/**
 * Auto-fill mapping:
 * Each activity maps to:
 *   { gasEmitted: string, unit: string }
 */
export const activityMetadata = {
  "Cement production (CO₂ from calcination)": { gasEmitted: "CO₂ emissions", unit: "" },
  "Lime production": { gasEmitted: "CO₂ emissions", unit: "" },
  "Aluminum smelting (PFCs)": { gasEmitted: "PFCs (CF₄, C₂F₆) emissions", unit: "" },
  "Glass manufacturing": { gasEmitted: "CO₂ emissions", unit: "" },
  "Iron and steel production (CO₂ from reduction of iron ore)": { gasEmitted: "CO₂ emissions", unit: "" },
  "Soda ash production": { gasEmitted: "CO₂ emissions", unit: "" },
  "Hydrogen production (from natural gas reforming)": { gasEmitted: "CO₂ emissions", unit: "" },
  "Carbide production": { gasEmitted: "CO₂ emissions", unit: "" },
  "Titanium dioxide production": { gasEmitted: "CO₂ / Cl₂ emissions", unit: "" },
  "Ethylene production (cracking process)": { gasEmitted: "CO₂ / CH₄ emissions", unit: "" },
  "Solvent use in paints and coatings": { gasEmitted: "VOCs emissions", unit: "" },
  "Dry cleaning operations": { gasEmitted: "VOCs (perchloroethylene, hydrocarbons) emissions", unit: "" },
  "Printing operations (ink solvents)": { gasEmitted: "VOCs emissions", unit: "" },
  "Adhesive and sealant application": { gasEmitted: "VOCs emissions", unit: "" },
  "Surface coating and finishing": { gasEmitted: "VOCs emissions", unit: "" },
  "Asphalt paving and roofing": { gasEmitted: "VOCs emissions", unit: "" },
  "Fuel dispensing at service stations": { gasEmitted: "VOCs emissions", unit: "" },
  "Industrial cleaning agents": { gasEmitted: "VOCs emissions", unit: "" },
  "Nitric acid production (N₂O)": { gasEmitted: "N₂O emissions", unit: "" },
  "Adipic acid production (N₂O)": { gasEmitted: "N₂O emissions", unit: "" },
  "Magnesium production (SF₆)": { gasEmitted: "SF₆ emissions", unit: "" },
  "Silicon production": { gasEmitted: "CO, CO₂, SiF₄ emissions", unit: "" },
  "Ferroalloy production": { gasEmitted: "CO, CO₂ emissions", unit: "" },
  "Ammonia production": { gasEmitted: "CO₂ emissions", unit: "" },
  "Urea production": { gasEmitted: "CO₂ emissions", unit: "" },
  "Methanol production": { gasEmitted: "CO₂ emissions", unit: "" },
  "Phosphoric acid production": { gasEmitted: "P₂O₅, minor CO₂ emissions", unit: "" },
  "Chlor-alkali production (CO₂ and Cl₂)": { gasEmitted: "Cl₂, CO₂ emissions", unit: "" },
  "Hydrogen production (SMR – Steam Methane Reforming)": { gasEmitted: "CO₂ emissions", unit: "" },
  "Catalytic cracking / reforming units": { gasEmitted: "CO₂ and CH₄ emissions", unit: "" },
  "Amine-based gas sweetening (acid gas removal)": { gasEmitted: "CO₂ emissions", unit: "" },
  "Sulfur recovery units (Claus process)": { gasEmitted: "CO₂ and SO₂ emissions", unit: "" },
  "Flue gas treatment (scrubbers, regeneration)": { gasEmitted: "CO₂ emissions", unit: "" },
  "Natural gas dehydration (glycol regeneration)": { gasEmitted: "CO₂ and CH₄ emissions", unit: "" },
  "Isomerization and alkylation processes": { gasEmitted: "CO₂ emissions", unit: "" },
  "Coke calcination (in delayed coking)": { gasEmitted: "CO₂ emissions", unit: "" },
  "Steam stripping / stripping towers": { gasEmitted: "CO₂ emissions", unit: "" },
  "Ethylene and Propylene production (via steam cracking)": { gasEmitted: "CO₂ and CH₄ emissions", unit: "" },
  "Methanol synthesis (from natural gas reforming)": { gasEmitted: "CO₂ emissions", unit: "" },
  "Ammonia production (via Haber-Bosch process)": { gasEmitted: "CO₂ emissions", unit: "" },
  "Nitric acid production": { gasEmitted: "CO₂ and N₂O emissions", unit: "" },
  "Adipic acid production": { gasEmitted: "CO₂ and N₂O emissions", unit: "" },
  "Carbon black manufacturing": { gasEmitted: "CO₂ emissions", unit: "" },
  "Formaldehyde production": { gasEmitted: "CO₂ emissions", unit: "" },
  "Vinyl chloride monomer (VCM) production": { gasEmitted: "CO₂ emissions", unit: "" },
  //
  "Terephthalic acid production (used in PET plastics)": { gasEmitted: "CO₂ emissions", unit: "" },
  "Acrylonitrile production": { gasEmitted: "CO₂ emissions", unit: "" },
  "Phthalic anhydride production": { gasEmitted: "CO₂ emissions", unit: "" },
  "Polyurethane precursor manufacturing (e.g., MDI, TDI)": { gasEmitted: "CO₂ emissions", unit: "" },
  "Ethylene oxide production": { gasEmitted: "CO₂ emissions", unit: "" },
  "Caprolactam production (used in nylon)": { gasEmitted: "CO₂ emissions", unit: "" },
  "Synthetic rubber production (e.g., SBR, BR)": { gasEmitted: "CO₂ emissions", unit: "" },
  "solvent recovery and distillation systems": { gasEmitted: "CO₂ emissions", unit: "" },
  "active pharmaceutical ingredient (API) synthesis reactions": { gasEmitted: "CO₂ emissions", unit: "" },
  "fermentation processes (e.g., antibiotics, insulin, enzymes)": { gasEmitted: "CO₂ emissions", unit: "" },
  "chemical neutralization reactions": { gasEmitted: "CO₂ emissions", unit: "" },
  "pH adjustment processes (e.g., acid/base reactions with carbonates)": { gasEmitted: "CO₂ emissions", unit: "" },
  "crystallization and recrystallization steps": { gasEmitted: "CO₂ emissions", unit: "" },
  "freeze-drying (lyophilization) processes": { gasEmitted: "CO₂ emissions", unit: "" },
  "clean-in-place (CIP) and sterilize-in-place (SIP) systems (chemical agents reacting and releasing gas)": { gasEmitted: "CO₂ emissions", unit: "" },
  "effluent treatment processes (e.g., aerobic/anaerobic biological oxidation)": { gasEmitted: "CO₂ emissions", unit: "" },
  "exothermic chemical coupling or synthesis reactions (e.g., peptide synthesis)": { gasEmitted: "CO₂ emissions", unit: "" },
  "sterilant or propellant preparation (e.g., EO, isopropyl alcohol)": { gasEmitted: "N₂O and CO₂ emissions", unit: "" },
  "buffer preparation (if involving carbonates or bicarbonates)": { gasEmitted: "CO₂ emissions", unit: "" },
  "high-shear granulation processes involving carbonates": { gasEmitted: "CO₂ emissions", unit: "" },
  "tablet coating or drying (with heat-induced chemical reactions)": { gasEmitted: "CO₂ emissions", unit: "" },
  "diagnostic reagent formulation processes": { gasEmitted: "CO₂ emissions", unit: "" },
  "lime-based flue gas desulfurization (FGD) units in coal power plants": { gasEmitted: "CO₂ emissions", unit: "" },
  "carbon capture and storage (CCS) processes (e.g., amine regeneration step)": { gasEmitted: "CO₂ emissions", unit: "" },
  "chemical looping processes in clean coal technologies": { gasEmitted: "CO₂ emissions", unit: "" },
  "biomass gasification (excluding combustion)": { gasEmitted: "CO₂ emissions", unit: "" },
  "anaerobic digestion (methane is converted to CO₂ if flared/oxidized during biogas handling)": { gasEmitted: "CO₂ emissions", unit: "" },
  "electrolysis-based hydrogen generation (if powered by fossil energy)": { gasEmitted: "CO₂ emissions", unit: "" },
  "battery recycling and chemical recovery processes (e.g., lithium-ion battery facilities)": { gasEmitted: "CO₂ emissions", unit: "" },
  "thermochemical energy storage systems (e.g., molten salt reactions)": { gasEmitted: "CO₂ emissions", unit: "" },
  "waste incineration with chemical additives or catalysts": { gasEmitted: "CO₂ and N₂O emissions", unit: "" },
  "geothermal fluid degassing (natural release of CO₂ from underground reservoirs)": { gasEmitted: "CO₂ emissions", unit: "" },
  "mineral carbonation in carbon-negative energy systems": { gasEmitted: "CO₂ emissions", unit: "" },
  "chemical reactions in concentrated solar thermal systems (heat transfer fluids degradation)": { gasEmitted: "CO₂ emissions", unit: "" },
  "fly ash or bottom ash treatment and neutralization (lime or acid reactions)": { gasEmitted: "CO₂ emissions", unit: "" },
  "water treatment plants (e.g., degassing of dissolved gases in boiler feedwater prep)": { gasEmitted: "CO₂ emissions", unit: "" },
  "synthetic fuel (e-fuel) production processes (non-combustion steps)": { gasEmitted: "CO₂ emissions", unit: "" },
  "Acid Gas Removal / Sweetening": { gasEmitted: "CO₂ emissions", unit: "" },
  "Sulphur Recovery Units (Claus Process)": { gasEmitted: "SO₂, CO₂ emissions", unit: "" },
  "Hydrogen Production (Steam Methane Reforming, SMR)": { gasEmitted: "CO₂ emissions", unit: "" },
  "Catalytic & Thermal Cracking": { gasEmitted: "CO₂ emissions", unit: "" },
  "Coke Production from Residuum": { gasEmitted: "CO₂ emissions", unit: "" },
  "Carbonate Treatment in Drilling Muds": { gasEmitted: "CO₂ emissions", unit: "" },
  "Flare Gas Stabilization": { gasEmitted: "CO₂ emissions", unit: "" },
  "Catalyst Regeneration (FCC Units)": { gasEmitted: "CO₂ emissions", unit: "" },
  "Hydrotreating / Hydrodesulfurization (HDS)": { gasEmitted: "CO₂ emissions", unit: "" },
  "Alkylation and Isomerization Units": { gasEmitted: "CO₂ emissions", unit: "" },
  "Calcination in Catalyst Preparation / Regeneration": { gasEmitted: "CO₂ emissions", unit: "" },
  "Coke Calcination (Anode-grade Coke)": { gasEmitted: "CO₂ emissions", unit: "" },
  "Acid Gas Removal (Amine or Selexol)": { gasEmitted: "CO₂ emissions", unit: "" },
  //
  "Dehydration (Glycol Regeneration)": { gasEmitted: "CO₂ emissions", unit: "" },
  "LNG Liquefaction / Regasification (Chemical Side)": { gasEmitted: "CH₄ (minor) emissions", unit: "" },
  "Carbonate Removal in CO₂ Capture Units (Amine / Solvent-based)": { gasEmitted: "CO₂ emissions", unit: "" },
  "Coal Carbonization / Coking": { gasEmitted: "CO₂, CH₄ emissions", unit: "" },
  "Coke Calcining / Sintering": { gasEmitted: "CO₂ emissions", unit: "" },
  "Coal Gasification / Liquefaction": { gasEmitted: "CO₂ emissions", unit: "" },
  "Limestone / Dolomite Use in Flue Gas Desulphurization (FGD)": { gasEmitted: "CO₂ emissions", unit: "" },
  "Carbonate Decomposition in Fluidized Bed Boilers": { gasEmitted: "CO₂ emissions", unit: "" },
  "CO₂ Capture Solvent Regeneration (Amine Scrubbing)": { gasEmitted: "CO₂ emissions", unit: "" },
  "Fuel Cell Electrochemical Processes (Reforming Fuel Cells)": { gasEmitted: "CO₂ emissions", unit: "" },
  "Biomass Gasification or Pyrolysis": { gasEmitted: "CO₂, CH₄ emissions", unit: "" },
  "Bioethanol Fermentation": { gasEmitted: "CO₂ emissions", unit: "" },
  "Biodiesel Transesterification": { gasEmitted: "CO₂ (minor) emissions", unit: "" },
  "Hydrogen from Electrolysis (if carbonates used)": { gasEmitted: "CO₂ (trace) emissions", unit: "" },
  "Renewable Methane Reforming / Biomethane Upgrading": { gasEmitted: "CO₂ emissions", unit: "" },
  "Carbonate / Bicarbonate Neutralization in API Synthesis": { gasEmitted: "CO₂ emissions", unit: "" },
  "Fermentation-based Production of Antibiotics, Vitamins, Enzymes": { gasEmitted: "CO₂ emissions", unit: "" },
  "CO₂ Use in Reaction Media or Extraction Systems": { gasEmitted: "CO₂ emissions", unit: "" },
  "Neutralization or Buffer Preparation Using Carbonates": { gasEmitted: "CO₂ emissions", unit: "" },
  "Lyophilization or Freeze-Drying Using CO₂ Refrigerants": { gasEmitted: "CO₂ emissions", unit: "" },
  "Anaerobic Wastewater or Biowaste Treatment (On-site)": { gasEmitted: "CH₄, CO₂ emissions", unit: "" },
  "On-site CO₂ Capture/Release in Chromatography Columns": { gasEmitted: "CO₂ emissions", unit: "" },
  "Use of Nitrous Oxide in Sterilization or Anaesthesia": { gasEmitted: "N₂O emissions", unit: "" },
  "Catalyst Regeneration with Carbonates or Acids": { gasEmitted: "CO₂ emissions", unit: "" },
  "Neutralization of Waste Streams (Carbonate Reactions)": { gasEmitted: "CO₂ emissions", unit: "" },
  //
  "Steam Cracking of Naphtha / Ethane": { gasEmitted: "CO₂ emissions", unit: "" },
  "Ethylene Oxide / Ethylene Glycol Production": { gasEmitted: "CO₂ emissions", unit: "" },
  "Ammonia / Urea Production": { gasEmitted: "CO₂ emissions", unit: "" },
  "Methanol Synthesis": { gasEmitted: "CO₂ emissions", unit: "" },
  "Hydrogenation / Hydrocracking Units": { gasEmitted: "CO₂ emissions", unit: "" },
  "Aromatics Production (Benzene, Toluene, Xylene)": { gasEmitted: "CO₂ emissions", unit: "" },
  "Polymerization Processes (Polyethylene, Polypropylene, PVC)": { gasEmitted: "CO₂ (minor) emissions", unit: "" },
  "CO₂ Stripping in Solvent Recovery / Purification": { gasEmitted: "CO₂ emissions", unit: "" },
  "Catalyst Calcination / Preparation": { gasEmitted: "CO₂ emissions", unit: "" },
  "Anaerobic Treatment of High-COD Waste Streams": { gasEmitted: "CH₄, CO₂ emissions", unit: "" },
  "Carbonate / Lime Use in Flue Gas Desulfurization (FGD)": { gasEmitted: "CO₂ emissions", unit: "" },
  "CO₂ Capture Solvent Regeneration (Post-combustion Capture)": { gasEmitted: "CO₂ emissions", unit: "" },
  "Coking / Carbonization in Solid Fuel Power Plants": { gasEmitted: "CO₂, CH₄ emissions", unit: "" },
  "Biomass Gasification or Pyrolysis for Power Generation": { gasEmitted: "CO₂, CH₄ emissions", unit: "" },
  "Hydrogen Production (for Fuel Cell or IGCC plants)": { gasEmitted: "CO₂ emissions", unit: "" },
  "Electrolytic Hydrogen Production (with Carbonates in Electrolyzer)": { gasEmitted: "CO₂ emissions", unit: "" },
  "CO₂ Venting from Supercritical CO₂ Power Cycles": { gasEmitted: "CO₂ emissions", unit: "" },
  "Anaerobic Wastewater Treatment (Power Plant Effluent)": { gasEmitted: "CH₄, CO₂ emissions", unit: "" },
  "Fuel Cell-based Power Generation (Reforming NG)": { gasEmitted: "CO₂ emissions", unit: "" },
};


export const processQualityControlOptions = [
  { value: "Highly Uncertain", label: "Highly Uncertain" },
  { value: "Uncertain", label: "Uncertain" },
  { value: "Fair", label: "Fair" },
  { value: "Good", label: "Good" },
  { value: "Exact", label: "Exact" },
];
