//Stationary
export const equipmentTypeOptions = [
  { value: "additive_blending_line_heaters", label: "Additive Blending Line Heaters" },
  { value: "adhesive_curing_oven", label: "Adhesive Curing Oven" },
  { value: "airport_ground_generator", label: "Airport Ground Generator" },
  { value: "amine_reboilers", label: "Amine Reboilers" },
  { value: "ammonia_or_methanol_synthesis_furnace", label: "Ammonia or Methanol Synthesis Furnace" },
  { value: "animal_cremator", label: "Animal Cremator" },
  { value: "annealing_furnace", label: "Annealing Furnace" },
  { value: "aquaculture_heater", label: "Aquaculture Heater" },
  { value: "asphalt_blowing_stills", label: "Asphalt Blowing Stills (if fired)" },
  { value: "asphalt_heater", label: "Asphalt Heater" },
  { value: "autoclaves_with_fuel_fired_boilers", label: "Autoclaves with Fuel-Fired Boilers" },
  { value: "auto_thermal_reformers", label: "Auto-thermal Reformers (ATRs)" },
  { value: "auxiliary_boilers", label: "Auxiliary Boilers" },
  { value: "backup_standby_generators", label: "Backup/Standby Generators" },
  { value: "bakery_oven", label: "Bakery Oven" },
  { value: "bench_scale_combustion_units", label: "Bench-scale Combustion Units" },
  { value: "biofuel_based_generator", label: "BioFuel Based Generator" },
  { value: "biogas_landfill_gas_engines", label: "Biogas/Landfill Gas Engines" },
  { value: "biohazard_incinerator", label: "Biohazard Incinerator" },
  { value: "biomass_boilers", label: "Biomass Boilers" },
  { value: "bitumen_tar_heater_units", label: "Bitumen / Tar Heater Units" },
  { value: "blast_furnace", label: "Blast Furnace" },
  { value: "brewing_kettle", label: "Brewing Kettle" },
  { value: "brick_kilns", label: "Brick Kilns" },
  { value: "building_heating_furnaces_stoves", label: "Building Heating Furnaces/Stoves" },
  { value: "campus_boiler", label: "Campus Boiler" },
  { value: "catalytic_oxidizers", label: "Catalytic Oxidizers" },
  { value: "catalytic_reforming_kilns", label: "Catalytic Reforming Catalyst Regeneration Kilns" },
  { value: "catering_oven", label: "Catering Oven" },
  { value: "caustic_recovery_unit", label: "Caustic Recovery Unit" },
  { value: "cement_kiln", label: "Cement Kiln" },
  { value: "ceramic_kilns", label: "Ceramic Kilns" },
  { value: "charcoal_grill", label: "Charcoal Grill" },
  { value: "charge_heaters", label: "Charge Heaters" },
  { value: "cheese_vat_heater", label: "Cheese Vat Heater" },
  { value: "chemical_reactor_heater", label: "Chemical Reactor Heater" },
  { value: "chp_units", label: "CHP (Combined Heat and Power) Units" },
  { value: "claus_plant_burners", label: "Claus Plant Burners (Sulfur Recovery Units)" },
  { value: "coal_fired_boiler", label: "Coal Fired Boiler" },
  { value: "coffee_roaster", label: "Coffee Roaster" },
  { value: "cogeneration_plant", label: "Cogeneration Plant" },
  { value: "coke_oven", label: "Coke Oven" },
  { value: "combined_cycle_hrsgs", label: "Combined Cycle Heat Recovery Steam Generators (HRSGs)" },
  { value: "combined_heat_power_buildings", label: "Combined Heat & Power (CHP) Units in Buildings" },
  { value: "combustion_turbines", label: "Combustion Turbines" },
  { value: "combustion_turbines_drive", label: "Combustion Turbines (for Power or Mechanical Drive)" },
  { value: "construction_site_generator", label: "Construction Site Generator" },
  { value: "cooking_range", label: "Cooking Range" },
  { value: "crematoria_furnaces", label: "Crematoria Furnaces" },
  { value: "crude_heaters", label: "Crude Heaters" },
  { value: "crude_oil_heaters", label: "Crude Oil Heaters" },
  { value: "cupola_furnaces", label: "Cupola Furnaces" },
  { value: "dairy_pasteurizer", label: "Dairy Pasteurizer" },
  { value: "dehydrogenation_reactor_furnaces", label: "Dehydrogenation Reactor Furnaces" },
  { value: "desalter_heaters", label: "Desalter Heaters" },
  { value: "dg_set", label: "DG Set" },
  { value: "diesel_engines", label: "Diesel Engines" },
  { value: "diesel_furnace", label: "Diesel Furnace" },
  { value: "diesel_generators", label: "Diesel Generators" },
  { value: "direct_fired_oxidizers", label: "Direct-fired Oxidizers" },
  { value: "distillation_unit", label: "Distillation Unit" },
  { value: "district_heating_plants", label: "District Heating Plants (Onsite)" },
  { value: "drying_oven", label: "Drying Oven" },
  { value: "dual_fuel_engines", label: "Dual-fuel Engines" },
  { value: "electric_generator_gas", label: "Electric Generator (Gas)" },
  { value: "emergency_backup_generator", label: "Emergency Backup Generator" },
  { value: "ethylene_cracking_furnaces", label: "Ethylene Cracking Furnaces" },
  { value: "ethylene_quench_furnaces", label: "Ethylene Quench Furnaces" },
  { value: "fcc_unit_regenerators", label: "FCC (Fluid Catalytic Cracking) Unit Regenerators" },
  { value: "fermentation_heater", label: "Fermentation Heater" },
  { value: "field_erected_boilers", label: "Field-Erected Boilers" },
  { value: "fired_experimental_reactors", label: "Fired Experimental Reactors" },
  { value: "fired_heaters", label: "Fired Heaters (e.g., for Distillation Units)" },
  { value: "fired_reboilers", label: "Fired Reboilers (vs. Steam-Heated Ones)" },
  { value: "fired_vaporizers", label: "Fired Vaporizers (e.g., LNG or Cryogenic Gas Applications)" },
  { value: "fish_dryer", label: "Fish Dryer" },
  { value: "flare_gas_recovery_combustors", label: "Flare Gas Recovery Combustors (Non-Flaring Systems)" },
  { value: "flare_pilots", label: "Flare Pilots (Continuous Gas Burners)" },
  { value: "food_cart_stove", label: "Food Cart Stove" },
  { value: "food_dryers", label: "Food Dryers" },
  { value: "food_processing_oven", label: "Food Processing Oven" },
  { value: "fuel_fired_pellet_dryers", label: "Fuel-fired Pellet Dryers" },
  { value: "gas_flaring_units", label: "Gas Flaring Units (Controlled/Operated by Company)" },
  { value: "gas_generators", label: "Gas Generators" },
  { value: "gas_lift_compressor_drivers", label: "Gas Lift Compressor Drivers (Fuel-Fired)" },
  { value: "gas_or_oil_space_heaters", label: "Gas- or Oil-Fired Space Heaters" },
  { value: "gas_sweetening_reboilers", label: "Gas Sweetening Reboilers (if Direct-Fired)" },
  { value: "gas_turbine", label: "Gas Turbine" },
  { value: "gas_fired_reciprocating_engines", label: "Gas-Fired Reciprocating Engines (for Compressors)" },
  { value: "glass_furnace", label: "Glass Furnace" },
  { value: "glass_lined_reactor_heating", label: "Glass-lined Reactor Heating Systems (Legacy Fuel-Fired)" },
  { value: "glycol_reboilers", label: "Glycol Reboilers" },
  { value: "grain_dryer", label: "Grain Dryer" },
  { value: "granulation_dryers", label: "Granulation Dryers (Fuel-Fired Tray or Fluidized Dryers)" },
  { value: "greenhouse_boiler", label: "Greenhouse Boiler" },
  { value: "heat_treatment_furnace", label: "Heat Treatment Furnace" },
  { value: "heated_separators", label: "Heated Separators / Heater Treaters" },
  { value: "heaters_furnaces", label: "Heaters & Furnaces" },
  { value: "hospital_sterilizer", label: "Hospital Sterilizer" },
  { value: "hot_air_sterilizers", label: "Hot Air Sterilizers (Fuel-Fired Versions)" },
  { value: "hot_oil_water_boilers", label: "Hot Oil /Water Boilers" },
  { value: "hot_water_heater", label: "Hot Water Heater" },
  { value: "hotel_boiler", label: "Hotel Boiler" },
  { value: "hvac_reheat_coils", label: "HVAC Reheat Coils (Fuel-Assisted)" },
  { value: "incinerator", label: "Incinerator" },
  { value: "incinerators_hazardous", label: "Incinerators (Hazardous Waste, Municipal Solid Waste)" },
  { value: "incinerators_expired_drugs", label: "Incinerators for Expired Drugs / Hazardous Waste" },
  { value: "industrial_boilers", label: "Industrial Boilers (Coal, Oil, Gas, Biomass)" },
  { value: "industrial_dryer", label: "Industrial Dryer" },
  { value: "industrial_kiln", label: "Industrial Kiln" },
  { value: "industrial_ovens", label: "Industrial Ovens (Baking, Curing, Drying)" },
  { value: "kerosene_heater", label: "Kerosene Heater" },
  { value: "lab_furnace", label: "Lab Furnace" },
  { value: "laundry_dryer", label: "Laundry Dryer" },
  { value: "lime_kilns", label: "Lime Kilns" },
  { value: "line_heaters", label: "Line Heaters" },
  { value: "liquid_waste_incinerators", label: "Liquid Waste Incinerators" },
  { value: "livestock_feed_dryer", label: "Livestock Feed Dryer" },
  { value: "lpg_cooktop", label: "LPG Cooktop" },
  { value: "marine_boiler", label: "Marine Boiler" },
  { value: "meat_smoker", label: "Meat Smoker" },
  { value: "medical_waste_incinerator", label: "Medical Waste Incinerator" },
  { value: "metal_foundry_furnace", label: "Metal Foundry Furnace" },
  { value: "military_base_generator", label: "Military Base Generator" },
  { value: "milk_evaporator", label: "Milk Evaporator" },
  { value: "mining_site_generator", label: "Mining Site Generator" },
  { value: "molasses_heater", label: "Molasses Heater" },
  { value: "natural_gas_boiler", label: "Natural Gas Boiler" },
  { value: "natural_gas_engines", label: "Natural Gas Engines" },
  { value: "natural_gas_heaters", label: "Natural Gas Heaters" },
  { value: "natural_gas_or_liquid_turbines", label: "Natural Gas or Liquid-Fueled Turbines (for Electricity Generation)" },
  { value: "natural_gas_fired_boilers", label: "Natural Gas-Fired Boilers" },
  { value: "oil_furnace", label: "Oil Furnace" },
  { value: "oil_rig_heater", label: "Oil Rig Heater" },
  { value: "oil_fired_space_heaters", label: "Oil-Fired Space Heaters" },
  { value: "package_boilers", label: "Package Boilers" },
  { value: "paint_booth_heater", label: "Paint Booth Heater" },
  { value: "paint_curing_oven", label: "Paint Curing Oven" },
  { value: "paper_dryers", label: "Paper Dryers" },
  { value: "paper_mill_boiler", label: "Paper Mill Boiler" },
  { value: "partial_oxidation_units", label: "Partial Oxidation Units" },
  { value: "peak_load_generator", label: "Peak Load Generator" },
  { value: "pellet_stove", label: "Pellet Stove" },
  { value: "pet_cremator", label: "Pet Cremator" },
  { value: "petrochemical_crackers", label: "Petrochemical Crackers/Reformers" },
  { value: "petrol_stove", label: "Petrol Stove" },
  { value: "pharmaceutical_dryer", label: "Pharmaceutical Dryer" },
  { value: "plastic_extruder_heater", label: "Plastic Extruder Heater" },
  { value: "polymerization_reactors", label: "Polymerization Reactors with Jacket Heating (Fuel-Fired)" },
  { value: "port_facility_generator", label: "Port Facility Generator" },
  { value: "poultry_house_heater", label: "Poultry House Heater" },
  { value: "powder_coating_oven", label: "Powder Coating Oven" },
  { value: "printing_press_heater", label: "Printing Press Heater" },
  { value: "process_furnaces", label: "Process Furnaces (Refineries, Petrochemicals, Steel)" },
  { value: "process_heaters", label: "Process Heaters" },
  { value: "propane_heater", label: "Propane Heater" },
  { value: "pulp_digester", label: "Pulp Digester" },
  { value: "pulverized_coal_boilers", label: "Pulverized Coal Boilers" },
  { value: "pumping_station_engines", label: "Pumping Station Engines (Oil & Gas, Water Pumping)" },
  { value: "railway_station_boiler", label: "Railway Station Boiler" },
  { value: "reboilers_distillation", label: "Reboilers (for Distillation Units)" },
  { value: "reboilers_aromatics", label: "Reboilers for Distillation of Aromatics" },
  { value: "reciprocating_engines", label: "Reciprocating Engines (Gas/Diesel Gensets)" },
  { value: "reforming_furnaces", label: "Reforming Furnaces" },
  { value: "regeneration_heaters", label: "Regeneration Heaters" },
  { value: "regenerative_thermal_oxidizers", label: "Regenerative Thermal Oxidizers (RTOs)" },
  { value: "reheating_furnaces", label: "Reheating Furnaces (Steel Mills, Forging)" },
  { value: "remote_site_generator", label: "Remote Site Generator" },
  { value: "restaurant_stove", label: "Restaurant Stove" },
  { value: "rice_dryer", label: "Rice Dryer" },
  { value: "rotary_dryers", label: "Rotary Dryers (Agriculture, Mining, Chemicals)" },
  { value: "rotary_kiln", label: "Rotary Kiln" },
  { value: "rubber_vulcanizer", label: "Rubber Vulcanizer" },
  { value: "seafood_boiler", label: "Seafood Boiler" },
  { value: "shipboard_generator", label: "Shipboard Generator" },
  { value: "sludge_incinerators", label: "Sludge Incinerators" },
  { value: "slug_catcher_line_heaters", label: "Slug Catcher Line Heaters" },
  { value: "smelters", label: "Smelters (Non-Ferrous Metallurgy)" },
  { value: "smelting_furnace", label: "Smelting Furnace" },
  { value: "space_heater", label: "Space Heater" },
  { value: "standby_generator", label: "Standby Generator" },
  { value: "steam_boilers_heating", label: "Steam Boilers for Heating" },
  { value: "steam_boilers_power", label: "Steam Boilers for Power" },
  { value: "steam_cracker_furnaces", label: "Steam Cracker Furnaces" },
  { value: "steam_methane_reformers", label: "Steam Methane Reformers (SMRs)" },
  { value: "steam_turbines", label: "Steam Turbines" },
  { value: "steamer", label: "Steamer" },
  { value: "street_vendor_grill", label: "Street Vendor Grill" },
  { value: "sugar_dryer", label: "Sugar Dryer" },
  { value: "sulfur_recovery_unit", label: "Sulfur Recovery Unit (SRU) Thermal Reactors" },
  { value: "tail_gas_treating_burners", label: "Tail Gas Treating Unit Burners" },
  { value: "tar_melter", label: "Tar Melter" },
  { value: "tea_dryer", label: "Tea Dryer" },
  { value: "tempering_furnace", label: "Tempering Furnace" },
  { value: "textile_boiler", label: "Textile Boiler" },
  { value: "textile_dryers", label: "Textile Dryers" },
  { value: "thermal_oxidizers_waste_gas", label: "Thermal Oxidizers (for Waste Gas)" },
  { value: "thermal_oxidizers_fuel_assisted", label: "Thermal Oxidizers (Fuel-Assisted)" },
  { value: "thermal_oxidizers_voc_control", label: "Thermal Oxidizers (VOC Control)" },
  { value: "turbine_driven_compressors", label: "Turbine-driven Compressors (e.g., Pipelines)" },
  { value: "vacuum_heaters", label: "Vacuum Heaters" },
  { value: "veterinary_incinerator", label: "Veterinary Incinerator" },
  { value: "waste_gas_fluid_incinerators", label: "Waste Gas/Fluid Incinerators (e.g. Produced Water Treatment)" },
  { value: "wellhead_line_heaters", label: "Wellhead Line Heaters (Natural Gas-Fired)" },
  { value: "wfi_generator_boilers", label: "WFI (Water for Injection) Generator Boilers" },
  { value: "winery_boiler", label: "Winery Boiler" },
  { value: "wood_stove", label: "Wood Stove" },
];

export const stakeholderOptions = [
  { value: "assembly", label: "Assembly" },
  { value: "asset_integrity", label: "Asset Integrity / Technical Integrity" },
  { value: "biostatistics", label: "Biostatistics / Statistical Programming" },
  { value: "blow_molding", label: "Blow Molding / Extrusion Trials Unit" },
  { value: "boiler_operations", label: "Boiler Operations" },
  { value: "carbon_accounting", label: "Carbon Accounting" },
  { value: "catalyst_additives", label: "Catalyst & Additives Handling (Petrochem Focus)" },
  { value: "catalyst_management", label: "Catalyst Management" },
  { value: "change_management", label: "Change Management" },
  { value: "chemical_operations", label: "Chemical Operations (Olefins, Aromatics, Polymers)" },
  { value: "clinical_data_management", label: "Clinical Data Management (CDM)" },
  { value: "clinical_operations", label: "Clinical Operations" },
  { value: "clinical_rnd", label: "Clinical Research & Development (Clinical R&D)" },
  { value: "clinical_trial_management", label: "Clinical Trial Management / Site Monitoring" },
  { value: "cmc", label: "CMC (Chemistry, Manufacturing & Controls)" },
  { value: "commercial_sales", label: "Commercial / Sales / Marketing" },
  { value: "compliance_audits", label: "Compliance & Audits" },
  { value: "compliance_legal", label: "Compliance / Legal / Regulatory Affairs" },
  { value: "compounding_blending", label: "Compounding & Blending" },
  { value: "compressed_air", label: "Compressed Air Systems" },
  { value: "corporate_banking", label: "Corporate Banking" },
  { value: "costing_budgeting", label: "Costing & Budgeting" },
  { value: "cracker_unit", label: "Cracker Unit Operations (e.g., Steam Cracker, Naphtha Cracker)" },
  { value: "customer_service", label: "Customer Service" },
  { value: "cybersecurity", label: "Cybersecurity" },
  { value: "data_analytics", label: "Data Analytics" },
  { value: "document_control", label: "Document Control" },
  { value: "drilling_completions", label: "Drilling & Completions" },
  { value: "etp", label: "Effluent Treatment Plant (ETP)" },
  { value: "emergency_response", label: "Emergency Response" },
  { value: "emissions_monitoring", label: "Emissions Monitoring" },
  { value: "energy_management", label: "Energy Management" },
  { value: "environmental_sustainability", label: "Environmental / Sustainability" },
  { value: "environmental_compliance", label: "Environmental Compliance" },
  { value: "erp_management", label: "ERP Management" },
  { value: "feedstock_coordination", label: "Feedstock Coordination / Feedstock Planning" },
  { value: "finance_accounting", label: "Finance & Accounting" },
  { value: "fire_emergency_response", label: "Fire & Emergency Response" },
  { value: "fire_safety", label: "Fire & Safety" },
  { value: "flare_management", label: "Flare Management / Flare Systems" },
  { value: "formulation_development", label: "Formulation Development (F&D)" },
  { value: "gas_processing", label: "Gas Processing Plant" },
  { value: "grid_operations", label: "Grid Operations" },
  { value: "hse", label: "Health, Safety & Environment (HSE / EHS)" },
  { value: "heat_treatment", label: "Heat Treatment" },
  { value: "hr", label: "Human Resources (HR)" },
  { value: "hvac_systems", label: "HVAC Systems" },
  { value: "hydrocarbon_accounting", label: "Hydrocarbon Accounting" },
  { value: "industrial_automation", label: "Industrial Automation" },
  { value: "inventory_management", label: "Inventory Management" },
  { value: "it_digitalization", label: "IT / OT / Digitalization" },
  { value: "it_infrastructure", label: "IT Infrastructure" },
  { value: "kaizen", label: "Kaizen / Continuous Improvement" },
  { value: "laboratory_services", label: "Laboratory Services" },
  { value: "lng_operations", label: "LNG Operations" },
  { value: "loan_processing", label: "Loan Processing" },
  { value: "logistics_dispatch", label: "Logistics & Dispatch" },
  { value: "logistics_supply_chain", label: "Logistics & Supply Chain" },
  { value: "maintenance_reliability", label: "Maintenance & Reliability" },
  { value: "manufacturing", label: "Manufacturing / Fabrication" },
  { value: "marine_operations", label: "Marine & Offshore Operations" },
  { value: "materials_science", label: "Materials Science / Polymer Lab" },
  { value: "mei", label: "Mechanical, Electrical, and Instrumentation (MEI)" },
  { value: "medical_affairs", label: "Medical Affairs / Scientific Liaison" },
  { value: "medical_records", label: "Medical Records" },
  { value: "medical_writing", label: "Medical Writing / Regulatory Writing" },
  { value: "monomer_production", label: "Monomer Production Units" },
  { value: "occupational_safety", label: "Occupational Health & Safety" },
  { value: "offsites_utilities", label: "Offsites & Utilities" },
  { value: "oil_processing", label: "Oil Processing Plant" },
  { value: "operations_production", label: "Operations / Production" },
  { value: "packaging", label: "Packaging" },
  { value: "packaging_development", label: "Packaging Development" },
  { value: "payroll_benefits", label: "Payroll & Benefits" },
  { value: "petroleum_economics", label: "Petroleum Economics / Planning" },
  { value: "pharmacovigilance", label: "Pharmacovigilance / Drug Safety" },
  { value: "pharmacy_services", label: "Pharmacy Services" },
  { value: "pipeline_operations", label: "Pipeline Operations & Integrity" },
  { value: "planning_scheduling", label: "Planning & Scheduling" },
  { value: "plc_programming", label: "PLC Programming" },
  { value: "polymer_operations", label: "Polymer Operations / Polymerization Units" },
  { value: "power_generation", label: "Power Generation" },
  { value: "process_engineering", label: "Process Engineering" },
  { value: "process_safety", label: "Process Safety / Technical Safety" },
  { value: "processing_plants", label: "Processing Plants" },
  { value: "procurement", label: "Procurement" },
  { value: "procurement_materials", label: "Procurement / Materials Management" },
  { value: "product_formulation", label: "Product Formulation / R&D / Application Testing" },
  { value: "production_operations", label: "Production Operations" },
  { value: "production_planning", label: "Production Planning & Control" },
  { value: "projects_engineering", label: "Projects / Engineering / Capital Projects" },
  { value: "quality_control", label: "Quality Control / Quality Assurance" },
  { value: "rnd_product_dev", label: "R&D / Product Development" },
  { value: "radiology", label: "Radiology Department" },
  { value: "recruitment_training", label: "Recruitment & Training" },
  { value: "refineries_operations", label: "Refineries Operations" },
  { value: "refining_operations", label: "Refining Operations / Units (e.g., CDU, FCC, Hydrocracker)" },
  { value: "regulatory_affairs", label: "Regulatory Affairs" },
  { value: "reservoir_engineering", label: "Reservoir Engineering" },
  { value: "resin_production", label: "Resin Production Operations" },
  { value: "retail_banking", label: "Retail Banking" },
  { value: "risk_management", label: "Risk Management" },
  { value: "scada_dcs", label: "SCADA / DCS Systems" },
  { value: "stp", label: "Sewage Treatment Plant (STP)" },
  { value: "stability_testing", label: "Stability Testing / ICH Compliance" },
  { value: "subsurface", label: "Subsurface / Geoscience" },
  { value: "supply_chain", label: "Supply Chain & Cold Chain Logistics" },
  { value: "surface_coating", label: "Surface Coating" },
  { value: "sustainability_reporting", label: "Sustainability Reporting" },
  { value: "technical_services", label: "Technical Services" },
  { value: "terminal_operations", label: "Terminal Operations / Tank Farm" },
  { value: "tool_room", label: "Tool Room" },
  { value: "transmission_distribution", label: "Transmission & Distribution" },
  { value: "treasury_operations", label: "Treasury Operations" },
  { value: "turnaround_shutdown", label: "Turnaround (TAR) / Shutdown Management" },
  { value: "utilities_energy", label: "Utilities & Energy" },
  { value: "vendor_management", label: "Vendor Management" },
  { value: "warehouse_management", label: "Warehouse Management" },
  { value: "waste_management", label: "Waste Management" },
  { value: "water_treatment", label: "Water Treatment" },
  { value: "welding_fabrication", label: "Welding & Fabrication" },
  { value: "well_services", label: "Well Services / Well Intervention" },
];


export const qualityControlOptions = [
  { value: "Highly Uncertain", label: "Highly Uncertain" },
  { value: "Uncertain", label: "Uncertain" },
  { value: "Fair", label: "Fair" },
  { value: "Good", label: "Good" },
  { value: "Exact", label: "Exact" },
];


// --- Fuel Type Options ---
export const fuelTypeOptions = [
  { value: "Gaseous Fuel", label: "Gaseous Fuel" },
  { value: "Bio Gaseous Fuel", label: "Bio Gaseous Fuel" },
  { value: "Liquid Fuel", label: "Liquid Fuel" },
  { value: "Bio Liquid Fuel", label: "Bio Liquid Fuel" },
  { value: "Solid Fuel", label: "Solid Fuel" },
  { value: "Biomass Fuel", label: "Biomass Fuel" },
];

// --- Fuel Names Based on Type ---
export const fuelNameOptionsByType = {
  "Gaseous Fuel": [
    { value: "Butane", label: "Butane" },
    { value: "CNG", label: "CNG" },
    { value: "LPG", label: "LPG" },
    { value: "Natural gas", label: "Natural gas" },
    { value: "Natural gas (100% mineral blend)", label: "Natural gas (100% mineral blend)" },
    { value: "LNG", label: "LNG" },
    { value: "Other petroleum gas", label: "Other petroleum gas" },
    { value: "Propane", label: "Propane" },
  ],
  "Bio Gaseous Fuel": [
    { value: "Biogas", label: "Biogas" },
    { value: "Landfill gas", label: "Landfill gas" },
  ],
  "Liquid Fuel": [
    { value: "Aviation spirit", label: "Aviation spirit" },
    { value: "Aviation turbine fuel", label: "Aviation turbine fuel" },
    { value: "Burning oil", label: "Burning oil" },
    { value: "Diesel (average biofuel blend)", label: "Diesel (average biofuel blend)" },
    { value: "Diesel (100% mineral diesel)", label: "Diesel (100% mineral diesel)" },
    { value: "Fuel oil", label: "Fuel oil" },
    { value: "Gas oil", label: "Gas oil" },
    { value: "Lubricants", label: "Lubricants" },
    { value: "Naphtha", label: "Naphtha" },
    { value: "Petrol (average biofuel blend)", label: "Petrol (average biofuel blend)" },
    { value: "Petrol (100% mineral petrol)", label: "Petrol (100% mineral petrol)" },
    { value: "Processed fuel oils - residual oil", label: "Processed fuel oils - residual oil" },
    { value: "Processed fuel oils - distillate oil", label: "Processed fuel oils - distillate oil" },
    { value: "Refinery miscellaneous", label: "Refinery miscellaneous" },
    { value: "Waste oils", label: "Waste oils" },
    { value: "Marine gas oil", label: "Marine gas oil" },
    { value: "Marine fuel oil", label: "Marine fuel oil" },
  ],
  "Bio Liquid Fuel": [
    { value: "Bioethanol", label: "Bioethanol" },
    { value: "Biodiesel ME", label: "Biodiesel ME" },
    { value: "Biomethane (compressed)", label: "Biomethane (compressed)" },
    { value: "Biodiesel ME (from used cooking oil)", label: "Biodiesel ME (from used cooking oil)" },
    { value: "Biodiesel ME (from tallow)", label: "Biodiesel ME (from tallow)" },
    { value: "Biodiesel HVO", label: "Biodiesel HVO" },
    { value: "Biopropane", label: "Biopropane" },
    { value: "Development diesel", label: "Development diesel" },
    { value: "Development petrol", label: "Development petrol" },
    { value: "Off road biodiesel", label: "Off road biodiesel" },
    { value: "Biomethane (liquified)", label: "Biomethane (liquified)" },
    { value: "Methanol (bio)", label: "Methanol (bio)" },
    { value: "Avtur (renewable)", label: "Avtur (renewable)" },
  ],
  "Solid Fuel": [
    { value: "Coal (industrial)", label: "Coal (industrial)" },
    { value: "Coal (electricity generation)", label: "Coal (electricity generation)" },
    { value: "Coal (domestic)", label: "Coal (domestic)" },
    { value: "Coking coal", label: "Coking coal" },
    { value: "Petroleum coke", label: "Petroleum coke" },
    {
      value: "Coal (electricity generation - home produced coal only)",
      label: "Coal (electricity generation - home produced coal only)",
    },
  ],
  "Biomass Fuel": [
    { value: "Wood logs", label: "Wood logs" },
    { value: "Wood chips", label: "Wood chips" },
    { value: "Wood pellets", label: "Wood pellets" },
    { value: "Grass/straw", label: "Grass/straw" },
  ],
};


// --- Fuel Consumption Units by Fuel Name ---
export const fuelUnitOptionsByName = {
  // common units (since all have these)
  default: [
    "Tonnes",
    "kg",
    "lb",
    "kwh",
    "MWh",
    "GWh",
    "Joules",
    "Gj",
    "Mj",
    "Tj",
    "Btu",
    "MMBtu",
  ],

  // extra units for specific fuels
  "Butane": ["Litres", "Gallons"],
  "CNG": ["Litres", "Gallons"],
  "Natural gas": ["m3", "ft3", "SCF", "in3"],
  "Natural gas (100% mineral blend)": ["m3", "ft3", "in3", "SCF"],
  "LPG": ["Litres", "Gallons"],
  "LNG": ["Litres", "Gallons"],
  "Other petroleum gas": ["Litres", "Gallons"],
  "Propane": ["Litres", "Gallons"],
  "Aviation spirit": ["Litres", "Gallons"],
  "Aviation turbine fuel": ["Litres", "Gallons"],
  "Burning oil": ["Litres", "Gallons"],
  "Petrol (average biofuel blend)": ["Litres", "Gallons"],
  "Diesel (average biofuel blend)": ["Litres", "Gallons"],
  "Diesel (100% mineral diesel)": ["Litres", "Gallons"],
  "Fuel oil": ["Litres", "Gallons"],
  "Gas oil": ["Litres", "Gallons"],
  "Lubricants": ["Litres", "Gallons"],
  "Naphtha": ["Litres", "Gallons"],
  "Petrol (100% mineral petrol)": ["Litres", "Gallons"],
  "Processed fuel oils - residual oil": ["Litres", "Gallons"],
  "Processed fuel oils - distillate oil": ["Litres", "Gallons"],
  "Waste oils": ["Litres", "Gallons"],
  "Marine gas oil": ["Litres", "Gallons"],
  "Marine fuel oil": ["Litres", "Gallons"],
  "Biodiesel ME": ["Litres", "Gallons"],
  "Biodiesel ME (from used cooking oil)": ["Litres", "Gallons"],
  "Biodiesel ME (from tallow)": ["Litres", "Gallons"],
  "Biodiesel HVO": ["Litres", "Gallons"],
  "Biopropane": ["Litres", "Gallons"],
  "Development diesel": ["Litres", "Gallons"],
  "Development petrol": ["Litres", "Gallons"],
  "Off road biodiesel": ["Litres", "Gallons"],
  "Methanol (bio)": ["Litres", "Gallons"],
  "Avtur (renewable)": ["Litres", "Gallons"],
  "Bioethanol": ["Litres", "Gallons"],
  "Biogas": ["Litres", "Gallons"],
  "Landfill gas": ["Litres", "Gallons"],
};